<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dashboard</name>
   <tag></tag>
   <elementGuidId>f1c4962a-1081-40b8-b701-166d51325596</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.top-level-menu-item.forced-active.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='top_level_menu_item_menu_item_154']/a)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#top-ribbon-menu div >> internal:has-text=&quot;Dashboard More more_vert Buzz oxd_menu_left Announcements Documents News oxd_men&quot;i >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>879c96bb-03eb-45d3-86b0-24e9ef857842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!!sref &amp;&amp; !menuTooltip</value>
      <webElementGuid>57576264-70d2-447b-8db4-e714fb088c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>top-level-menu-item forced-active active</value>
      <webElementGuid>8daa93c3-4cce-44a3-b6d9-3c72d4f98a7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ui-sref</name>
      <type>Main</type>
      <value>dashboard</value>
      <webElementGuid>3229df6f-2018-4828-85a8-a3b1f6e6f985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ui-sref-active</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>80e3d855-6d35-4007-a420-1408c9aee2be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>toggleShowSubmenu()</value>
      <webElementGuid>00ba90ca-b08a-47ac-88da-8c6af6b87002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>more_menu_current_child_menu_dashboard_index</value>
      <webElementGuid>8564163f-0fd5-4d24-a22b-fd916566988a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>70213ed3-a4da-4102-828a-58fbd4b858cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/dashboard</value>
      <webElementGuid>23d9229d-71fb-4bcb-b432-e3641167ffe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard  </value>
      <webElementGuid>8b771ed7-e9c9-4ad2-9392-4adecb8f52a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-ribbon-menu&quot;)/div[@class=&quot;top-ribbon-menu-more-items&quot;]/top-level-menu-item[1]/div[@id=&quot;top_level_menu_item_menu_item_154&quot;]/a[@class=&quot;top-level-menu-item forced-active active&quot;]</value>
      <webElementGuid>3370eed6-1169-44d1-95a7-4364c225bdc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='top_level_menu_item_menu_item_154']/a)[2]</value>
      <webElementGuid>d1560ed4-b5bb-4da0-b7f2-12763ff8c434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Dashboard')])[2]</value>
      <webElementGuid>a22fbdf6-711b-40e2-9794-00857abf4dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Candidate Records'])[1]/following::a[1]</value>
      <webElementGuid>f6a4056e-174e-4c0d-a0cc-c9e170dee282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee Records'])[1]/following::a[2]</value>
      <webElementGuid>f93a842a-bf91-462d-af4d-2be0646e8bf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='more_vert'])[1]/preceding::a[1]</value>
      <webElementGuid>30b97816-22ea-42de-a46c-817c5977b7ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#/dashboard')])[3]</value>
      <webElementGuid>cc14f809-cd68-4057-b2c3-4986901075ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/top-level-menu-item/div/a</value>
      <webElementGuid>82373b2b-5277-42dc-bbae-bd281ebec5ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/dashboard' and (text() = 'Dashboard  ' or . = 'Dashboard  ')]</value>
      <webElementGuid>63f3c809-4865-474b-bb4a-40dd170f4ac0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
