<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_More  more_vert</name>
   <tag></tag>
   <elementGuidId>36fdeebc-1ef9-473f-a7b8-e87c4df96dcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.top-ribbon-menu-more-items > top-level-menu-item > div.top-level-menu-item-container > a.top-level-menu-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='top-ribbon-menu']/div[3]/top-level-menu-item/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;More more_vert&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f7aaa40c-76df-4e0d-95a6-c6e225ad9e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!sref &amp;&amp; !menuTooltip</value>
      <webElementGuid>d240aade-4b84-46d6-be1e-b8a6fe98b396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-href</name>
      <type>Main</type>
      <value>{{href}}</value>
      <webElementGuid>f82fe6e2-0741-4ec3-a063-978255799518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>top-level-menu-item </value>
      <webElementGuid>b8317e9b-0740-4fd0-a493-e05038df3762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-target</name>
      <type>Main</type>
      <value>{{target}}</value>
      <webElementGuid>84252ef9-0eca-4400-87a1-dfc812c81f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>toggleShowSubmenu()</value>
      <webElementGuid>06f293e4-98ff-41d9-874c-246db8358a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>more_menu_child_menu_top_more</value>
      <webElementGuid>3a836e8e-5e88-47ef-9fc8-7f3b03a624a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>37c14f0d-1eff-4de8-96c2-62bc15985409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>More  more_vert</value>
      <webElementGuid>e99a34b3-4e4e-4de7-aac6-55eef256d559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-ribbon-menu&quot;)/div[@class=&quot;top-ribbon-menu-more-items&quot;]/top-level-menu-item[1]/div[@class=&quot;top-level-menu-item-container&quot;]/a[@class=&quot;top-level-menu-item&quot;]</value>
      <webElementGuid>efd390e7-4a92-4542-b30e-eaa90af5addb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top-ribbon-menu']/div[3]/top-level-menu-item/div/a</value>
      <webElementGuid>25e32edf-88f6-47b2-903f-fd97d5fdbfd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Candidate Records'])[1]/following::a[1]</value>
      <webElementGuid>d9739570-7a64-4ebd-a74d-8771e5dd07dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee Records'])[1]/following::a[2]</value>
      <webElementGuid>4dee20cd-3b38-4b76-bd14-c8359ee5e509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Info'])[2]/preceding::a[1]</value>
      <webElementGuid>7538e994-b02f-4657-8793-2ac94043ea7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/top-level-menu-item/div/a</value>
      <webElementGuid>eab8c67c-8a47-4001-b9c7-d2caf17dc771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'More  more_vert' or . = 'More  more_vert')]</value>
      <webElementGuid>88ac6c89-64e0-4296-b9b8-2c4a37ee1aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top-ribbon-menu']/div[3]/top-level-menu-item[2]/div/a</value>
      <webElementGuid>9bc1a7d6-75c7-4f00-ba00-85949070155f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::a[1]</value>
      <webElementGuid>aa09976e-d340-467b-80f9-247fe11b949d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Candidate Records'])[1]/following::a[2]</value>
      <webElementGuid>9e476d58-6fa6-41e6-b3cb-414e123a6b94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buzz'])[2]/preceding::a[1]</value>
      <webElementGuid>cb69a5e1-1f3a-4bbb-801b-df9e4c17474c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/top-level-menu-item[2]/div/a</value>
      <webElementGuid>e89e416c-d79b-44a4-9abd-c132ded92fcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
