<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_oxd_home_menu</name>
   <tag></tag>
   <elementGuidId>6a458d4e-7fa6-45f6-82cb-838de71965b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.basic-navigation > a.tooltipped</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='top-ribbon-menu']/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;oxd_home_menu&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6f8326fb-92d8-4a57-bd5b-c8533fc36307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ui-sref</name>
      <type>Main</type>
      <value>dashboard</value>
      <webElementGuid>cbee17ac-7421-46f2-b924-192ac636b898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ui-sref-active</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>7152dc54-8fdd-4ecc-ae4a-b4d4b1d49552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>def6d85e-ab00-4dc8-8590-f93f950f96e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-position</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>2127592b-a1bb-4aeb-b17a-c98cc892a7bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tooltipped</value>
      <webElementGuid>1f1e5994-1635-4aa7-afb5-0e49e0f8abcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>menu_home</value>
      <webElementGuid>81d9df56-3464-4c6e-a94c-12d4874f1194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/dashboard</value>
      <webElementGuid>f5941183-c431-4502-a1bf-e257133a2011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-id</name>
      <type>Main</type>
      <value>b6f4bdc2-58c6-96d3-615e-5f85c0198928</value>
      <webElementGuid>8f512f4f-b591-4529-ac4b-a3368df89e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>oxd_home_menu</value>
      <webElementGuid>8cbe7851-4ae4-4973-b038-6fc40da9c829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-ribbon-menu&quot;)/div[@class=&quot;top-ribbon-menu-basic-navigation menu-separator&quot;]/div[@class=&quot;basic-navigation&quot;]/a[@class=&quot;tooltipped&quot;]</value>
      <webElementGuid>47cfedac-dfc4-4536-a385-949d611105eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top-ribbon-menu']/div/div/a</value>
      <webElementGuid>5fc8b051-97a1-4cae-b321-8e7c3b71d440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout from all browsers'])[1]/following::a[1]</value>
      <webElementGuid>7e47cb12-44b5-4992-987f-9034040f7cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_drop_down'])[1]/following::a[2]</value>
      <webElementGuid>10ca0511-6a71-4b06-8e7e-c4638e545f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::a[1]</value>
      <webElementGuid>2e5af9c0-cd61-4ee1-bdfc-9b20c9683234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/dashboard')]</value>
      <webElementGuid>d422706f-9e2d-478e-a0e0-87294f9166c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//top-menu/div/div/div/div/a</value>
      <webElementGuid>5c87ca0b-986f-4f87-9b5e-172bc52fa67f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/dashboard' and (text() = 'oxd_home_menu' or . = 'oxd_home_menu')]</value>
      <webElementGuid>1d7d04d5-55e3-48c1-bbd3-deb74f967a54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
