<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_oxd_menu_left Qualifications</name>
   <tag></tag>
   <elementGuidId>fbf9988c-1f52-4abc-8b88-f25f9929848a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='top-ribbon-menu']/div[3]/top-level-menu-item[2]/div/sub-menu-container/div/div[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;oxd_menu_left Qualifications&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>956b0814-0c66-4785-980e-729cd3e8401a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!menu.uiSref &amp;&amp; maxLevels > 0</value>
      <webElementGuid>43302574-7fb1-40b8-bee0-926c13b960f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-focus</name>
      <type>Main</type>
      <value>showSubmenu($index)</value>
      <webElementGuid>73af07b7-4636-4115-85c4-4e4d674573da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-mouseover</name>
      <type>Main</type>
      <value>showSubmenu($index)</value>
      <webElementGuid>b14d99ef-e598-411b-bbd0-1ff9185dea8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-href</name>
      <type>Main</type>
      <value>{{menu.href}}</value>
      <webElementGuid>c81b8e99-6e6b-4de0-96c2-668bc95f5b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub-menu-item-link truncate</value>
      <webElementGuid>301a4237-1e5f-4a0e-befd-f905e5e59223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-target</name>
      <type>Main</type>
      <value>{{menu.target}}</value>
      <webElementGuid>0ca7d321-2ac3-455f-9e9f-dcd6516ddf54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>more_menu_child_menu_admin_Qualifications</value>
      <webElementGuid>456baf55-9046-499a-9bc1-168ff27e8c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3771534b-b475-4a1f-b031-27f4d4b43e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>oxd_menu_left Qualifications </value>
      <webElementGuid>5fbfa72f-39c4-4046-bbb8-ba31a04b59ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-ribbon-menu&quot;)/div[@class=&quot;top-ribbon-menu-more-items&quot;]/top-level-menu-item[2]/div[@class=&quot;top-level-menu-item-container&quot;]/sub-menu-container[@class=&quot;level-1-sub-menu opened&quot;]/div[@class=&quot;sub-menu-container&quot;]/div[@class=&quot;sub-menu-item&quot;]/a[@class=&quot;sub-menu-item-link truncate&quot;]</value>
      <webElementGuid>46eaef22-207c-495a-adff-f918804330d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top-ribbon-menu']/div[3]/top-level-menu-item[2]/div/sub-menu-container/div/div[5]/a</value>
      <webElementGuid>eb77cf44-22de-43f9-8a07-c7c3a032e588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Competency List'])[2]/following::a[1]</value>
      <webElementGuid>fc5f990c-bc81-49ef-92f8-61e94eea4db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='oxd_menu_left'])[3]/following::a[2]</value>
      <webElementGuid>c9e6e033-4928-4638-979a-7d0ecd9e8e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skills'])[2]/preceding::a[1]</value>
      <webElementGuid>882e70a7-bdaf-4261-b936-45d6f7082185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//top-level-menu-item[2]/div/sub-menu-container/div/div[5]/a</value>
      <webElementGuid>60c96ccc-ba69-470f-992e-4d57fb75da85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'oxd_menu_left Qualifications ' or . = 'oxd_menu_left Qualifications ')]</value>
      <webElementGuid>9713b820-16c5-4222-8023-ec54e8bbb72c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top-ribbon-menu']/div[3]/top-level-menu-item[2]/div/sub-menu-container/div/div[6]/a</value>
      <webElementGuid>3b1719fa-5383-42e3-9fb7-2babe1546882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//top-level-menu-item[2]/div/sub-menu-container/div/div[6]/a</value>
      <webElementGuid>94af49cd-cd03-4be3-984a-05489af6d24f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top-ribbon-menu']/div[3]/top-level-menu-item[2]/div/sub-menu-container/div/div[4]/a</value>
      <webElementGuid>827e2073-735e-44b0-bed4-4ef2880b5514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//top-level-menu-item[2]/div/sub-menu-container/div/div[4]/a</value>
      <webElementGuid>e733e58d-e53f-4796-b604-5e987dd116ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
