<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_oxd_home_menu</name>
   <tag></tag>
   <elementGuidId>f7702197-c4fa-48e1-af21-b58c45174477</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.tooltipped > i.material-icons</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='top-ribbon-menu']/div/div/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;oxd_home_menu&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>fbb9c1ce-1e05-4bf3-8141-77c92407c50e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons</value>
      <webElementGuid>0f343316-5580-49ce-982d-2ceaaad9b499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>oxd_home_menu</value>
      <webElementGuid>2b3a1aaf-ed8e-4a6d-b8f6-6e5a4e2a79b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-ribbon-menu&quot;)/div[@class=&quot;top-ribbon-menu-basic-navigation menu-separator&quot;]/div[@class=&quot;basic-navigation&quot;]/a[@class=&quot;tooltipped&quot;]/i[@class=&quot;material-icons&quot;]</value>
      <webElementGuid>b4d29513-5e31-4112-8191-5a21e6260d1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top-ribbon-menu']/div/div/a/i</value>
      <webElementGuid>32432cf5-1c12-43f0-bdf3-38ceff4e6a88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout from all browsers'])[1]/following::i[1]</value>
      <webElementGuid>ff343e04-4d2e-4070-8474-7ae34373eb0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_drop_down'])[1]/following::i[1]</value>
      <webElementGuid>da765324-bbf0-4d2c-b6c0-a3a5d38cf589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::i[1]</value>
      <webElementGuid>44a1d684-cbb8-4fc0-9d98-e90a08c2d89d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee List'])[1]/preceding::i[1]</value>
      <webElementGuid>321f19c7-4f1f-44be-aa20-8bfba04cda90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='oxd_home_menu']/parent::*</value>
      <webElementGuid>5971c751-2e53-4e2c-b244-49bc574b19a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//top-menu/div/div/div/div/a/i</value>
      <webElementGuid>040f38d1-723d-4376-b4a5-6fb496c3d357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'oxd_home_menu' or . = 'oxd_home_menu')]</value>
      <webElementGuid>10aa5dc6-f5e7-4077-b521-8a96d36eaa7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
