<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Supervisor_circle list-photo</name>
   <tag></tag>
   <elementGuidId>907eeb9e-4175-4610-a8c6-52e65374520b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.circle.list-photo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='employeeListTable']/tbody/tr/td/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;0204 Frank Aaron Art Director Freelance Quality assurance (QA) 0009 - Cost center (QA) Canadian Development Center&quot;i] >> internal:role=link >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>904b376d-423f-4628-a241-3e5602c18da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>circle list-photo</value>
      <webElementGuid>4cfa5ea0-f096-4a19-bcac-80dd5bc5ac48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!employee.photo</value>
      <webElementGuid>61ac00a4-2fd1-4687-b23a-317b92668001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-src</name>
      <type>Main</type>
      <value>images/default-photo.png</value>
      <webElementGuid>b2557f4e-6332-4106-90fb-874c1ee408c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/default-photo.png</value>
      <webElementGuid>eb607c96-aba1-46e3-b84d-622dfa800ded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employeeListTable&quot;)/tbody[1]/tr[1]/td[1]/a[@class=&quot;table-cell-link&quot;]/img[@class=&quot;circle list-photo&quot;]</value>
      <webElementGuid>a843285e-b646-4249-8eb2-cfa72da9d40a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='employeeListTable']/tbody/tr/td/a/img</value>
      <webElementGuid>983949c7-9c9f-48c0-81eb-76f24ec97b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a/img</value>
      <webElementGuid>e31f04b6-e120-4bc6-aa76-371276d466c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/default-photo.png']</value>
      <webElementGuid>3a188cd3-e86d-4957-ae27-240e490568fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
