<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Supervisor_circle list-photo</name>
   <tag></tag>
   <elementGuidId>907eeb9e-4175-4610-a8c6-52e65374520b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.circle.list-photo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='employeeListTable']/tbody/tr/td/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;0204 Frank Aaron Art Director Freelance Quality assurance (QA) 0009 - Cost center (QA) Canadian Development Center&quot;i] >> internal:role=link >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ca5f9356-99d7-4848-baf4-e8f594ed2072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>circle list-photo</value>
      <webElementGuid>3d42b4e6-3608-4a4d-aa2e-98569f3912c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!employee.photo</value>
      <webElementGuid>bbf65d0e-43ed-4be1-b6de-3806b79469ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-src</name>
      <type>Main</type>
      <value>images/default-photo.png</value>
      <webElementGuid>e3c33625-ddda-4681-851a-93226762cd91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/default-photo.png</value>
      <webElementGuid>135bb2d4-9553-4c49-ac55-aa8d0d3c65ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employeeListTable&quot;)/tbody[1]/tr[1]/td[1]/a[@class=&quot;table-cell-link&quot;]/img[@class=&quot;circle list-photo&quot;]</value>
      <webElementGuid>7d2464b0-f4ec-4aba-83ee-2307c24c3603</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='employeeListTable']/tbody/tr/td/a/img</value>
      <webElementGuid>1ddc82db-4cfc-49a1-b9b5-f913b30ba061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a/img</value>
      <webElementGuid>0a0d1ad4-41a5-4156-9e68-7c2f88e5dced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/default-photo.png']</value>
      <webElementGuid>9366d9fe-8f51-4cf5-b029-50e39defcb1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
