<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__first-name-box</name>
   <tag></tag>
   <elementGuidId>14dcb6c7-5683-46e5-9b66-374fd177c75b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#first-name-box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='first-name-box']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;First Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83514a08-bbb9-4001-afb5-59c8746f1513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control first-name-box ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>f9e718d7-e0c4-4f65-b43c-f8775862b0cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>first-name-box</value>
      <webElementGuid>a8a76bc2-2ddf-49ca-98ce-d9e9813992a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First Name</value>
      <webElementGuid>0f4b662e-c277-48f2-b85b-d8877d4289d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>420a31b6-1520-40f4-8809-35904b1658a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>usedForm.readonly</value>
      <webElementGuid>13c956b6-27aa-4d26-9df8-0d432e5d6272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>ngModel.firstName</value>
      <webElementGuid>58513756-7ddb-4b73-8dd9-36c4dfa10798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;first-name-box&quot;)</value>
      <webElementGuid>e551a5ed-c089-4ee5-bef6-cd8e2f41d634</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='first-name-box']</value>
      <webElementGuid>1dacd764-f028-461f-b949-378accc891d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-holder']/div/div/div/div[2]/form/oxd-decorator/div/div[2]/div/div/div/div/div/oxd-employee-name-input/div/input</value>
      <webElementGuid>db25df18-7f3a-4bd2-9b18-a2513098a2f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//oxd-employee-name-input/div/input</value>
      <webElementGuid>3f7fe7d4-78c6-40c7-bf89-6c6340447a06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'first-name-box' and @placeholder = 'First Name' and @type = 'text']</value>
      <webElementGuid>e6484bea-cb8d-4157-9920-78470ea2dda2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
