<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__last-name-box</name>
   <tag></tag>
   <elementGuidId>09fa28b8-4eb2-4b69-8c32-9b1c2189fa2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#last-name-box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='last-name-box']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Last Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1ae16b2-91b6-49ed-8d6b-55de5e3202ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid ng-empty ng-not-empty-add ng-pristine-remove ng-dirty-add ng-valid-parse-add ng-animate ng-empty-remove</value>
      <webElementGuid>9ee815d8-28e5-4172-b5c9-1cbe0040cb09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>last-name-box</value>
      <webElementGuid>3879d693-5dd4-4d89-b1d4-bf9350d93825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>56adc2bf-a654-4a52-a558-18a78dcc2c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e7740444-2d07-479b-84b6-130974f4ec50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>usedForm.readonly</value>
      <webElementGuid>7ee8f86c-0642-4165-aa0d-a32b6d98c862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>ngModel.lastName</value>
      <webElementGuid>2c39c8d9-3107-422f-892f-a7ee22b6c068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-animate</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>bb852317-d452-48f1-833c-dc4487927e78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;last-name-box&quot;)</value>
      <webElementGuid>356a7abb-f2d2-4230-88f5-1d44f995bb1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='last-name-box']</value>
      <webElementGuid>0e8e022e-d440-499b-9dda-eb6692e123a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-holder']/div/div/div/div[2]/form/oxd-decorator/div/div[2]/div/div/div/div/div/oxd-employee-name-input/div/input[3]</value>
      <webElementGuid>6ad58e43-2d47-4b3b-a35a-f792466baad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>430aea4f-dda0-4c2b-a9e1-3016c875008a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'last-name-box' and @placeholder = 'Last Name' and @type = 'text']</value>
      <webElementGuid>c700d1fb-2a56-4cd3-98c9-9a196ce6cec8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
