<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Select --AustraliaAustralia offic_24b8d4</name>
   <tag></tag>
   <elementGuidId>38d058b7-2a07-4cd8-9357-80c6ff4ca6c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#location</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='location']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Location*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a8265b18-056f-4992-a667-8416c03ac998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!form.translate</value>
      <webElementGuid>333a6eda-5af5-4215-860e-b81036436955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>location</value>
      <webElementGuid>79514b4e-76d4-46d4-85a9-23769928e76b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>model['location']</value>
      <webElementGuid>63881826-da28-490e-8279-cd472f811a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model-options</name>
      <type>Main</type>
      <value>form.ngModelOptions</value>
      <webElementGuid>aa40b5d9-1cdc-4b48-85c3-8fb5204d65ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>form.readonly</value>
      <webElementGuid>fa4f86a9-d2b7-46bf-aa27-e106ee819791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sf-changed</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>e1e0b346-38b0-437e-876f-8921d34b59a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-dropdown</value>
      <webElementGuid>6da5c429-e988-4b1a-991f-4ce64f2f5dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'loader-is-showing' : form.showLoader}</value>
      <webElementGuid>a74460c7-05da-477d-ab38-66cf4691c40d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>schema-validate</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>09a9889c-3396-415a-a089-3ac725368816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>item.value as item.name group by item.group for item in form.titleMap</value>
      <webElementGuid>0ae51bd6-2b63-4e5f-af0c-2724e0026ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ohrm-make-element-non-pristine</name>
      <type>Main</type>
      <value>form.removePristine</value>
      <webElementGuid>32e3abb0-9d22-4f87-bcd9-4bc435fa1b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>location</value>
      <webElementGuid>1b9cbe36-bfb3-4cdf-a7c6-49449cc0d46a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Select --AustraliaAustralia officeCanadaCanadian Development CenterFranceFrance OfficeGermanyGerman OfficeIndiaIndia OfficeJamaicaJamaica training centerMexicoMexico OfficePhilippinesPhilippine call centerSingaporeSingapore Regional HQSouth AfricaSouth Africa Satellite OfficeUnited KingdomUK OfficeUnited StatesUS Office</value>
      <webElementGuid>afc0c638-ffc9-4885-a954-29f94bacf365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;location&quot;)</value>
      <webElementGuid>25eb1ac1-4b1c-4f50-97f8-de78c35e67c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='location']</value>
      <webElementGuid>faf09ccd-b2fa-4808-b979-0d705becd963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-holder']/div/div/div/div[2]/form/oxd-decorator/div/div[2]/div/div[3]/div/div[3]/div/div/select</value>
      <webElementGuid>b7d7d1b5-bb54-4415-8ce8-089bc6549e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::select[1]</value>
      <webElementGuid>a85f9ec8-d7b4-42cf-bebc-c4e3b443b42d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Select --'])[2]/preceding::select[1]</value>
      <webElementGuid>84c006ce-2465-4a9c-b3d9-14d2d318e596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Select --'])[3]/preceding::select[1]</value>
      <webElementGuid>b2d0873f-475b-4582-a87e-90246645bb43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/select</value>
      <webElementGuid>4f9ab23e-24f7-4d05-8885-dd2f523e0497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'location' and @name = 'location' and (text() = '-- Select --AustraliaAustralia officeCanadaCanadian Development CenterFranceFrance OfficeGermanyGerman OfficeIndiaIndia OfficeJamaicaJamaica training centerMexicoMexico OfficePhilippinesPhilippine call centerSingaporeSingapore Regional HQSouth AfricaSouth Africa Satellite OfficeUnited KingdomUK OfficeUnited StatesUS Office' or . = '-- Select --AustraliaAustralia officeCanadaCanadian Development CenterFranceFrance OfficeGermanyGerman OfficeIndiaIndia OfficeJamaicaJamaica training centerMexicoMexico OfficePhilippinesPhilippine call centerSingaporeSingapore Regional HQSouth AfricaSouth Africa Satellite OfficeUnited KingdomUK OfficeUnited StatesUS Office')]</value>
      <webElementGuid>657f889c-8097-4169-88b5-a317efef7219</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
