<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Select --AustraliaAustralia offic_24b8d4</name>
   <tag></tag>
   <elementGuidId>38d058b7-2a07-4cd8-9357-80c6ff4ca6c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='location']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#location</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Location*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c411adb2-4a73-4624-b8ab-58ac0742ae3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!form.translate</value>
      <webElementGuid>f860ea7e-b5f7-45b1-aab7-0154eb8161b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>location</value>
      <webElementGuid>7ac3990a-c288-4baa-b8aa-a95ccd0f2865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>model['location']</value>
      <webElementGuid>2ffcdeae-7b88-4085-aa2a-ae58c7bb5d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model-options</name>
      <type>Main</type>
      <value>form.ngModelOptions</value>
      <webElementGuid>242f53d1-f0dc-499a-8e51-5111aa1dd6e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>form.readonly</value>
      <webElementGuid>1e21fca0-efb7-44ae-aa30-dab2a1961bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sf-changed</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>1db2a822-01ad-4f47-8ff2-294a7da0c16a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-dropdown</value>
      <webElementGuid>ac09d804-145f-4455-9bab-55a65f8e5867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'loader-is-showing' : form.showLoader}</value>
      <webElementGuid>0f4c78a1-3e1e-45e0-95a4-2f9cc445e1ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>schema-validate</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>c8d09cfd-b37f-4817-a710-86a040f0c513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>item.value as item.name group by item.group for item in form.titleMap</value>
      <webElementGuid>61fadfb2-e6ba-4bc8-bc10-d509f3b29f57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ohrm-make-element-non-pristine</name>
      <type>Main</type>
      <value>form.removePristine</value>
      <webElementGuid>ecce1632-05ba-4330-993d-dd126677c65c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>location</value>
      <webElementGuid>f2610fc2-cf67-4161-91ad-86f6a9f4240b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Select --AustraliaAustralia officeCanadaCanadian Development CenterFranceFrance OfficeGermanyGerman OfficeIndiaIndia OfficeJamaicaJamaica training centerMexicoMexico OfficePhilippinesPhilippine call centerSingaporeSingapore Regional HQSouth AfricaSouth Africa Satellite OfficeUnited KingdomUK OfficeUnited StatesUS Office</value>
      <webElementGuid>0142a56d-0be6-4680-ba6f-d21323101fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;location&quot;)</value>
      <webElementGuid>3fc93060-4514-4148-b728-139afc545247</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='location']</value>
      <webElementGuid>d04b5f38-d599-4264-bdb9-3b1f60609bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-holder']/div/div/div/div[2]/form/oxd-decorator/div/div[2]/div/div[3]/div/div[3]/div/div/select</value>
      <webElementGuid>f8e67e7b-590a-4d72-b842-5195e1769731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::select[1]</value>
      <webElementGuid>3486ab82-c24c-42d7-9ee2-f53128b5be3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Select --'])[2]/preceding::select[1]</value>
      <webElementGuid>25857e76-8605-45d2-8618-3364b18f930d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Select --'])[3]/preceding::select[1]</value>
      <webElementGuid>7c330695-d445-4e98-b23e-bdd518b99e0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/select</value>
      <webElementGuid>f969d981-db06-4a9e-a2b4-13094e867868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'location' and @name = 'location' and (text() = '-- Select --AustraliaAustralia officeCanadaCanadian Development CenterFranceFrance OfficeGermanyGerman OfficeIndiaIndia OfficeJamaicaJamaica training centerMexicoMexico OfficePhilippinesPhilippine call centerSingaporeSingapore Regional HQSouth AfricaSouth Africa Satellite OfficeUnited KingdomUK OfficeUnited StatesUS Office' or . = '-- Select --AustraliaAustralia officeCanadaCanadian Development CenterFranceFrance OfficeGermanyGerman OfficeIndiaIndia OfficeJamaicaJamaica training centerMexicoMexico OfficePhilippinesPhilippine call centerSingaporeSingapore Regional HQSouth AfricaSouth Africa Satellite OfficeUnited KingdomUK OfficeUnited StatesUS Office')]</value>
      <webElementGuid>aff42e56-ef39-4a4a-8878-e199960a3f20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
