<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_21</name>
   <tag></tag>
   <elementGuidId>ad4fa8bf-d819-492c-942a-6e6ff3b60ff9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P738298928_table > tbody > tr:nth-of-type(4) > td:nth-of-type(5) > div.picker__day.picker__day--infocus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='P738298928_table']/tbody/tr[4]/td[5]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;2024-11-21&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f9edeb8d-a6fe-4260-9c66-2ac2ad2d8995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>picker__day picker__day--infocus</value>
      <webElementGuid>f6efd434-6a3e-45d6-b479-6dd9f9646ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pick</name>
      <type>Main</type>
      <value>1732161600000</value>
      <webElementGuid>07c07994-44fe-4afd-aa70-f358c33be9d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>1c9bf196-5613-4b91-8601-af79ea18ab6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>2024-11-21</value>
      <webElementGuid>153ef8df-be76-4860-b5ea-83e844d73eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>01e399e7-fc14-4686-ae38-f2ee45c5c303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P738298928_table&quot;)/tbody[1]/tr[4]/td[5]/div[@class=&quot;picker__day picker__day--infocus&quot;]</value>
      <webElementGuid>2ce587ff-ebf7-4071-a204-e5da4d7d7fd1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='P738298928_table']/tbody/tr[4]/td[5]/div</value>
      <webElementGuid>ec53db4e-0bce-48ac-b5c9-43eab1b49d85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[4]/following::div[26]</value>
      <webElementGuid>9d2fcfc3-4544-44ed-8bf5-90f8b5e6fec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[2]/following::div[26]</value>
      <webElementGuid>0abd9d3c-4421-4ce6-b980-8a6b648cbbc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[2]/preceding::div[17]</value>
      <webElementGuid>46320d3f-ce75-40cc-9a44-78c8c5e8c559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[2]/preceding::div[17]</value>
      <webElementGuid>c613dcee-2da6-43f7-83fc-249edf49c95c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//sf-decorator[3]/div/span/span/div/div/div/div/div/div[2]/table/tbody/tr[4]/td[5]/div</value>
      <webElementGuid>9e7fc547-755e-4018-b0f0-e0aa616261ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '21' or . = '21')]</value>
      <webElementGuid>d12385c7-89c4-4f91-bafb-8f7ff10e93b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
