<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__picker__nav--next</name>
   <tag></tag>
   <elementGuidId>de8e5ff5-759f-4a8b-871f-9af7a69f1530</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P738298928_root > div.picker__holder > div.picker__frame > div.picker__wrap > div.picker__box > div.picker__calendar-container > div.picker__header > div.picker__nav--next</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='P738298928_root']/div/div/div/div/div[2]/div/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Next month&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>25eb40b5-0e57-46b5-a2cc-c85fb772ce13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>picker__nav--next</value>
      <webElementGuid>4c339bdb-daa9-4d68-8452-05e6da620a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nav</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3a5462f4-dae1-43ad-b26c-36b7bfc00b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2a7beb9a-7e7b-485b-a89e-54a01a55ffec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>P738298928_table</value>
      <webElementGuid>7a2ad17a-4118-4a2e-bfb3-dc894a491b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Next month</value>
      <webElementGuid>0535812e-96c7-4661-97f4-741c5879ccce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P738298928_root&quot;)/div[@class=&quot;picker__holder&quot;]/div[@class=&quot;picker__frame&quot;]/div[@class=&quot;picker__wrap&quot;]/div[@class=&quot;picker__box&quot;]/div[@class=&quot;picker__calendar-container&quot;]/div[@class=&quot;picker__header&quot;]/div[@class=&quot;picker__nav--next&quot;]</value>
      <webElementGuid>167cf0d7-f054-4270-9b48-60f7bb48edc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P738298928_root']/div/div/div/div/div[2]/div/div[4]</value>
      <webElementGuid>d5589e95-65d8-47a1-b427-c1fb64fb46ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='▼'])[7]/following::div[2]</value>
      <webElementGuid>26a6f0cd-4ff5-4172-8c8f-4c06b63d77b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='December'])[3]/following::div[3]</value>
      <webElementGuid>1f6ab6fa-533b-472a-a719-33dad55e29f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[3]/preceding::div[1]</value>
      <webElementGuid>285a20a8-06ef-4b10-9b7a-260b5e5429d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M'])[2]/preceding::div[1]</value>
      <webElementGuid>caca7c4e-3923-4434-99fb-0635c216e4ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//sf-decorator[3]/div/span/span/div/div/div/div/div/div[2]/div/div[4]</value>
      <webElementGuid>32dd3d07-43f5-449f-8b8d-875155ed0a8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'Next month']</value>
      <webElementGuid>f8ec42d2-0a8e-43ba-b6ad-4435dc5030e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
