<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_3</name>
   <tag></tag>
   <elementGuidId>eb3b9873-862c-43b5-97fe-b0611e15546f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='P128362100_table']/tbody/tr/td[5]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P128362100_table > tbody > tr > td:nth-of-type(5) > div.picker__day.picker__day--infocus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;2025-04-03&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3ef5fb4e-c33d-4cf6-98c6-f281d156f77e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>picker__day picker__day--infocus</value>
      <webElementGuid>fcd732cf-3431-4bd9-bc3c-f4394f7b007c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pick</name>
      <type>Main</type>
      <value>1743649200000</value>
      <webElementGuid>05979603-919d-482c-8001-26c1d73ce32b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>c137e313-fc50-4db2-9ba7-e5a6ec4dcf15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>2025-04-03</value>
      <webElementGuid>7ea061da-2b77-4d95-9d13-0c21c46dee90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>fdcfd5ec-9b30-4078-9c3c-b7199bec003e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P128362100_table&quot;)/tbody[1]/tr[1]/td[5]/div[@class=&quot;picker__day picker__day--infocus&quot;]</value>
      <webElementGuid>52b1ab17-90b0-435c-8eef-ead877aa4070</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='P128362100_table']/tbody/tr/td[5]/div</value>
      <webElementGuid>e9d3273a-f375-44dc-85d6-1067090b1f69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[4]/following::div[5]</value>
      <webElementGuid>b84f3ba5-07a3-40d7-8f14-e0a6cf1e669b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[2]/following::div[5]</value>
      <webElementGuid>1829bb2c-0b87-4138-a8aa-6bf340d1aaf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[2]/preceding::div[38]</value>
      <webElementGuid>21521416-9e3e-4eab-9ddc-73d312cda038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[2]/preceding::div[38]</value>
      <webElementGuid>d9b3840c-f855-43c3-a43b-7400c048edd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//sf-decorator[3]/div/span/span/div/div/div/div/div/div[2]/table/tbody/tr/td[5]/div</value>
      <webElementGuid>3f445dc0-df3c-40c9-8e12-d42ec41ee793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '3' or . = '3')]</value>
      <webElementGuid>009478ce-8588-446d-99ce-941a9df47195</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
