<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__select-dropdown</name>
   <tag></tag>
   <elementGuidId>9d9b0ed7-73c3-4ba6-b132-2a3386406595</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.select-wrapper.picker__select--year > input.select-dropdown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='2023']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#P2050049110_root >> internal:role=textbox >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f9915d7-6401-4020-bfa1-92e396c60ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b7634ee9-bec8-4469-9a25-2819e1c31a3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-dropdown</value>
      <webElementGuid>c0133c24-a787-422d-83e8-de972dca6a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cb5062c0-9c6c-42dd-82cd-ed6309c75e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-activates</name>
      <type>Main</type>
      <value>select-options-7aa25883-8578-51dd-4f68-d511f26cca33</value>
      <webElementGuid>9a67e82b-abc8-41b3-b829-f7ae35a74138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2023</value>
      <webElementGuid>8a35c9e0-5628-48df-95ec-0fe38df7c760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P2050049110_root&quot;)/div[@class=&quot;picker__holder&quot;]/div[@class=&quot;picker__frame&quot;]/div[@class=&quot;picker__wrap&quot;]/div[@class=&quot;picker__box&quot;]/div[@class=&quot;picker__calendar-container&quot;]/div[@class=&quot;picker__header&quot;]/div[@class=&quot;select-wrapper picker__select--year&quot;]/input[@class=&quot;select-dropdown&quot;]</value>
      <webElementGuid>1ea85644-a737-4132-a304-5da07a8ea12d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='2023']</value>
      <webElementGuid>5488ad50-1f99-4d79-a8f2-9e26edda0d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P2050049110_root']/div/div/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>9e3089be-453e-4a16-ad11-1b6ea7fe46d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>690921d7-3522-4466-a5d6-065de321a820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>1abef470-17f6-4792-b962-7b86fe802748</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
