<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1976</name>
   <tag></tag>
   <elementGuidId>9cfc07eb-b84c-40d4-9bb9-9d80c4de1355</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(53) > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='select-options-7aa25883-8578-51dd-4f68-d511f26cca33']/li[53]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>span >> internal:has-text=/^1976$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>491404e4-fb33-4f63-8bb0-ac7f97b673fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1976</value>
      <webElementGuid>ba0d8f00-9f22-4c8c-a6b9-2e40e1112982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-options-7aa25883-8578-51dd-4f68-d511f26cca33&quot;)/li[53]/span[1]</value>
      <webElementGuid>fb3ffb7e-28fa-4485-8865-2fb0c302db5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select-options-7aa25883-8578-51dd-4f68-d511f26cca33']/li[53]/span</value>
      <webElementGuid>56b338cd-e376-48d7-afb1-df92e157cb4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='▼'])[2]/following::span[53]</value>
      <webElementGuid>7f4b48ac-1b26-46aa-9191-484ac7b79b46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='December'])[1]/following::span[54]</value>
      <webElementGuid>fa169c2b-ee81-4425-ac51-78cc7a4bf5fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[1]/preceding::span[49]</value>
      <webElementGuid>e6494f77-27ab-4ef4-9b8b-dafa2fe8bd8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M'])[1]/preceding::span[49]</value>
      <webElementGuid>ba16d07e-27cb-42c2-9619-61bcb0837402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1976']/parent::*</value>
      <webElementGuid>d3d3fba9-0ce9-4b75-9e55-3260d94d40c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[53]/span</value>
      <webElementGuid>14e7c4e2-2c14-47f6-8d4d-9d3b16804dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '1976' or . = '1976')]</value>
      <webElementGuid>198dad66-8a2e-4632-9037-a32bd5686718</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
