<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Male</name>
   <tag></tag>
   <elementGuidId>071b63f7-5d71-45ca-8ccf-c2db8199a81b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select-options-5b99d964-a81a-5e04-fbb6-28a0fb2e4427 > li:nth-of-type(3) > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='select-options-5b99d964-a81a-5e04-fbb6-28a0fb2e4427']/li[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>span >> internal:has-text=/^Male$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>15f75818-ce71-45dd-9f9d-333f35cc4f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Male</value>
      <webElementGuid>509385a7-57d1-4e16-863e-6e7868b90b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-options-5b99d964-a81a-5e04-fbb6-28a0fb2e4427&quot;)/li[3]/span[1]</value>
      <webElementGuid>5542a4f3-560a-420e-82df-2773a8001f1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select-options-5b99d964-a81a-5e04-fbb6-28a0fb2e4427']/li[3]/span</value>
      <webElementGuid>fe2c486a-9f28-44c5-8eae-717849285c4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Female'])[1]/following::span[1]</value>
      <webElementGuid>2eb70195-a6fa-4881-bdda-c45c914b5552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Select --'])[3]/following::span[2]</value>
      <webElementGuid>d3382426-d826-4f26-8f92-f0fbb15852db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non-Binary'])[1]/preceding::span[1]</value>
      <webElementGuid>94658c59-521d-46d3-981a-b652a8ed4f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[1]/preceding::span[2]</value>
      <webElementGuid>41562acf-f825-4f40-b668-7dd1e67b321d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Male']/parent::*</value>
      <webElementGuid>723c9ca7-9d42-45ca-a3de-87bacf503168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//sf-decorator[3]/div/div/ul/li[3]/span</value>
      <webElementGuid>70351925-8f86-4bfa-9112-4b328f1b58b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Male' or . = 'Male')]</value>
      <webElementGuid>ebe26cb5-a032-4962-8519-a0fec149a4f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
