<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Canadian</name>
   <tag></tag>
   <elementGuidId>1f319a9c-0361-4f25-9e3d-4cdec3983ae9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='select-options-65ccbf99-043a-d1cc-460e-4abeb03e6ba3']/li[36]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(36) > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>span >> internal:has-text=&quot;Canadian&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1bf80cfc-f82e-45e6-aadc-e81f5c6db3db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Canadian</value>
      <webElementGuid>d252c5ae-0535-458d-94ca-adeaa4d1a6e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-options-65ccbf99-043a-d1cc-460e-4abeb03e6ba3&quot;)/li[36]/span[1]</value>
      <webElementGuid>4e015377-6e1c-453b-a6c8-6c6d86126978</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select-options-65ccbf99-043a-d1cc-460e-4abeb03e6ba3']/li[36]/span</value>
      <webElementGuid>45d1d215-8cfa-4c7b-8a94-15eaca168166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cameroonian'])[1]/following::span[1]</value>
      <webElementGuid>78a2c675-eb24-4b3b-a0b2-584af6a774f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cambodian'])[1]/following::span[2]</value>
      <webElementGuid>729d3efb-85fd-44d9-8aa9-9cdad5edf684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cape Verdean'])[1]/preceding::span[1]</value>
      <webElementGuid>3ba2712a-c50b-42e2-98c0-be9e53482a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Central African'])[1]/preceding::span[2]</value>
      <webElementGuid>bd243c8f-3a31-44f6-95f4-77cddfeeb72a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Canadian']/parent::*</value>
      <webElementGuid>9871d1a0-4ef2-4f73-9c89-12bdc48b15b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[36]/span</value>
      <webElementGuid>99abbd58-7ab8-4044-93df-c359f17155ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Canadian' or . = 'Canadian')]</value>
      <webElementGuid>00413689-3809-4169-8a3c-c3eca8e997a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select-options-245d1bc2-2763-d5e6-d810-79f54a555eec']/li[36]/span</value>
      <webElementGuid>94ad316f-4469-4a10-9a91-3e21728b0504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//sf-decorator/div/div/ul/li[36]/span</value>
      <webElementGuid>e2ecbc6b-7321-496e-8947-509a36f81930</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
