<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Single</name>
   <tag></tag>
   <elementGuidId>f472a782-1ab9-40bf-b1b2-377484192fa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select-options-14a24d3c-6447-5f20-ea4c-39e695201c38 > li:nth-of-type(3) > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='select-options-14a24d3c-6447-5f20-ea4c-39e695201c38']/li[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>span >> internal:has-text=&quot;Single&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0a1e5c4a-3a08-40d8-bc89-0e1731d3bbfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Single</value>
      <webElementGuid>554340a0-3e39-41ec-b79e-91f13afbd213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-options-14a24d3c-6447-5f20-ea4c-39e695201c38&quot;)/li[3]/span[1]</value>
      <webElementGuid>c39ab6d8-8b53-4cf0-a256-52e355860c87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select-options-14a24d3c-6447-5f20-ea4c-39e695201c38']/li[3]/span</value>
      <webElementGuid>9ebfde0d-51e5-4605-a5da-d6977798f1c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Married'])[1]/following::span[1]</value>
      <webElementGuid>8e7c53bf-547e-4db3-bb8f-91f365a208b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Select --'])[1]/following::span[2]</value>
      <webElementGuid>e2ecbff7-339a-4f27-b436-d1f8c79b935a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other'])[2]/preceding::span[1]</value>
      <webElementGuid>75869f9c-315b-43c9-b917-a3e43c572d4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marital Status'])[1]/preceding::span[2]</value>
      <webElementGuid>f9e4dfe3-3f7d-4771-ba55-1a4a047ccb28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Single']/parent::*</value>
      <webElementGuid>4ebbcec8-f643-47de-bf5f-34b67451bab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//sf-decorator[2]/div/div/ul/li[3]/span</value>
      <webElementGuid>9cc1b72a-5f80-4b06-8cbd-45872ad27741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Single' or . = 'Single')]</value>
      <webElementGuid>59d13949-b09e-4e85-a1ea-ff3b9837ecab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
