<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_2025</name>
   <tag></tag>
   <elementGuidId>ebd39d69-1b4d-41b7-9194-d1b7b087888a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='select-options-db3f741e-9254-9ef3-6429-bb9eaaf9c09c']/li[22]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select-options-db3f741e-9254-9ef3-6429-bb9eaaf9c09c > li:nth-of-type(22) > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>span >> internal:has-text=/^2025$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>21e3810d-6480-4a4a-bc82-54f5bab019ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2025</value>
      <webElementGuid>724c19ba-f147-4c95-a467-965813e575f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-options-db3f741e-9254-9ef3-6429-bb9eaaf9c09c&quot;)/li[22]/span[1]</value>
      <webElementGuid>d5a9ec6e-df0a-4f4c-8595-a95d6de5bf88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select-options-db3f741e-9254-9ef3-6429-bb9eaaf9c09c']/li[22]/span</value>
      <webElementGuid>d3b14c2c-dd68-482d-a3f8-8828fafb3989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='▼'])[5]/following::span[22]</value>
      <webElementGuid>67395871-248c-4dfc-a061-f77b033f2905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='December'])[2]/following::span[23]</value>
      <webElementGuid>5213ce22-0bfd-4c6b-b383-4fa82ab45b20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[3]/preceding::span[20]</value>
      <webElementGuid>bd92364d-8a6e-41cb-8ac0-db00a7d26b4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M'])[2]/preceding::span[20]</value>
      <webElementGuid>f4cbe37f-6b0f-41aa-a260-e85ba0aa7ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2025']/parent::*</value>
      <webElementGuid>8d9e62be-d80c-4ca5-8bce-0c3b2d7952be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[22]/span</value>
      <webElementGuid>2dd86517-dccf-4766-b652-2e0e966d356e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '2025' or . = '2025')]</value>
      <webElementGuid>bdee6467-f8db-4c16-8229-285a8c8cb28f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
