<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Male</name>
   <tag></tag>
   <elementGuidId>071b63f7-5d71-45ca-8ccf-c2db8199a81b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='select-options-2d46365a-c3b7-655c-35c7-523536fe5b03']/li[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select-options-2d46365a-c3b7-655c-35c7-523536fe5b03 > li:nth-of-type(3) > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>span >> internal:has-text=/^Male$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7076dae7-062a-4a08-9a32-c1527104ee50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Male</value>
      <webElementGuid>5017382e-cb29-47d9-8912-ad0240f7a168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-options-2d46365a-c3b7-655c-35c7-523536fe5b03&quot;)/li[3]/span[1]</value>
      <webElementGuid>674f45d3-3a1a-496c-81a0-0e39c8adbe50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select-options-2d46365a-c3b7-655c-35c7-523536fe5b03']/li[3]/span</value>
      <webElementGuid>2ff1f49a-337f-4669-9cab-4f2d8cf2f700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Female'])[1]/following::span[1]</value>
      <webElementGuid>b307180a-6f8e-4fa2-ac82-eadb29918278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Select --'])[3]/following::span[2]</value>
      <webElementGuid>ba6171cf-74cd-4a1e-9645-855c1cc52658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non-Binary'])[1]/preceding::span[1]</value>
      <webElementGuid>deaf10df-b6d0-48d4-ae74-2d37d3eaaf17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[1]/preceding::span[2]</value>
      <webElementGuid>6991d4dd-fcd6-4c2d-9830-f029155b08dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Male']/parent::*</value>
      <webElementGuid>5af176bc-ffde-4f4f-b268-b7e7a17980dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//sf-decorator[3]/div/div/ul/li[3]/span</value>
      <webElementGuid>9e37bc33-78e8-44e4-ae7a-af3fa88f55ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Male' or . = 'Male')]</value>
      <webElementGuid>873ff983-2d25-4605-96a9-de9fe0b42c1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select-options-5b99d964-a81a-5e04-fbb6-28a0fb2e4427']/li[3]/span</value>
      <webElementGuid>fe2c486a-9f28-44c5-8eae-717849285c4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
