<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_29</name>
   <tag></tag>
   <elementGuidId>85c3c5bc-265d-44a0-ace8-057f7a1720f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.picker__day.picker__day--infocus.picker__day--today.picker__day--highlighted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='P1538971411_table']/tbody/tr[5]/td[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;2024-04-28 2024-04-29 2024-04-30&quot;i] >> internal:label=&quot;2024-04-29&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>950edcd5-2e7a-4966-931a-b0b4d2c2452a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>picker__day picker__day--infocus picker__day--today picker__day--highlighted</value>
      <webElementGuid>93743eb3-6bc9-444c-97b7-9e99fc561555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pick</name>
      <type>Main</type>
      <value>1714359600000</value>
      <webElementGuid>671a9e82-2026-40ac-a3c2-8a0724184fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>51f6d245-bfe3-4ab0-b207-482da3c9ab0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>2024-04-29</value>
      <webElementGuid>02abe4c1-8732-4649-947a-b8337c4faee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5476d952-5eba-466f-84e5-977b5c72355c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>29</value>
      <webElementGuid>66d9257f-be11-4178-b71d-972e47884a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P1538971411_table&quot;)/tbody[1]/tr[5]/td[2]/div[@class=&quot;picker__day picker__day--infocus picker__day--today picker__day--highlighted&quot;]</value>
      <webElementGuid>5ee522a7-82bc-4248-8d38-700e47a1ab4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='P1538971411_table']/tbody/tr[5]/td[2]/div</value>
      <webElementGuid>71b0d250-f42f-4766-83c8-55554846aadb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[6]/following::div[30]</value>
      <webElementGuid>3cae74ba-8cc5-42e2-9cf0-4ddbdcf707e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[3]/following::div[30]</value>
      <webElementGuid>d28dacb7-5dd6-4c8e-a6c4-577fff566108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[3]/preceding::div[13]</value>
      <webElementGuid>377864ed-d5b3-4c09-abfb-5ef334ee7804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[3]/preceding::div[13]</value>
      <webElementGuid>d2f06092-b64e-4fc5-854b-0a2957334f94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//oxd-decorator[6]/div/div/div[2]/div[6]/div/div/div/div/div[2]/table/tbody/tr[5]/td[2]/div</value>
      <webElementGuid>65f0a159-9a99-4f5c-ab2f-f92154e95077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '29' or . = '29')]</value>
      <webElementGuid>543bd8d2-bfac-47ff-95e0-b3dc1d50e3e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
