<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_30</name>
   <tag></tag>
   <elementGuidId>3d11053b-8155-4240-ac33-e471506ea9d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P1552954971_table > tbody > tr:nth-of-type(5) > td:nth-of-type(6) > div.picker__day.picker__day--infocus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='P1552954971_table']/tbody/tr[5]/td[6]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;2027-04-30&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>09c82068-92ba-4ffc-8caa-d41478bbd690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>picker__day picker__day--infocus</value>
      <webElementGuid>c34c33b9-f19f-4e32-baf9-c6f706b9f1d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pick</name>
      <type>Main</type>
      <value>1809054000000</value>
      <webElementGuid>e9f7f9f1-bc6b-4e0e-829f-085ae8ad9c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>1d62d73a-c9d3-4c89-bf64-7496d217db8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>2027-04-30</value>
      <webElementGuid>b0b8064b-8837-49e2-8f38-98df21453809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>e19979b1-bfdd-4fb9-8e59-1cd8d66eb1d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P1552954971_table&quot;)/tbody[1]/tr[5]/td[6]/div[@class=&quot;picker__day picker__day--infocus&quot;]</value>
      <webElementGuid>fc952ed1-0f52-4e89-8643-945e9659c16b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='P1552954971_table']/tbody/tr[5]/td[6]/div</value>
      <webElementGuid>998deca8-cb31-4db8-a0e7-9c2bc78b7447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[8]/following::div[34]</value>
      <webElementGuid>577212de-4ffa-4713-b92c-c8200ce5ac4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[4]/following::div[34]</value>
      <webElementGuid>a8398ea8-a58a-465d-b9b9-1038c16f3570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[4]/preceding::div[9]</value>
      <webElementGuid>df9349cd-871f-41c8-8605-fc2968f84d32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[4]/preceding::div[9]</value>
      <webElementGuid>db0f46b6-aade-4768-ac21-bddbad495d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//oxd-decorator[6]/div/div[2]/div[2]/div[6]/div/div/div/div/div[2]/table/tbody/tr[5]/td[6]/div</value>
      <webElementGuid>f8038b2b-5f28-4933-8401-f1a5d539c05e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '30' or . = '30')]</value>
      <webElementGuid>3c3fd86c-649f-4a02-8918-75877522e6f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
