<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_15</name>
   <tag></tag>
   <elementGuidId>31bf5fd4-5046-4bef-889b-d0f72a7c68d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P815199236_table > tbody > tr:nth-of-type(3) > td:nth-of-type(5) > div.picker__day.picker__day--infocus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='P815199236_table']/tbody/tr[3]/td[5]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;2024-08-11 2024-08-12 2024-08-13 2024-08-14 2024-08-15 2024-08-16 2024-08-17&quot;i] >> internal:label=&quot;2024-08-15&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>25db6e08-3574-4bb3-bfb6-d0457910c39c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>picker__day picker__day--infocus</value>
      <webElementGuid>e0c719f4-baf8-4348-a9bb-8861276e43c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pick</name>
      <type>Main</type>
      <value>1723690800000</value>
      <webElementGuid>85dd1467-91d8-494e-bcc6-78354ded404e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>4996a476-df7b-4c21-bbe5-dc9f7fb6f068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>2024-08-15</value>
      <webElementGuid>6e3406eb-b5cd-4f09-a15f-cb1ee4b030db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>dfd5198f-8d8b-405a-bc13-72fe46edf10a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P815199236_table&quot;)/tbody[1]/tr[3]/td[5]/div[@class=&quot;picker__day picker__day--infocus&quot;]</value>
      <webElementGuid>68dff051-bad9-489d-b1e7-46581e9d45ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='P815199236_table']/tbody/tr[3]/td[5]/div</value>
      <webElementGuid>3272f9a5-0e7c-457a-938d-c7498f899d5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[4]/following::div[19]</value>
      <webElementGuid>bcb3cc13-ecc6-422a-8376-0f379ed16b73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[2]/following::div[19]</value>
      <webElementGuid>40dae6d7-d490-4faf-ab8f-7b5710a4e9b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[2]/preceding::div[24]</value>
      <webElementGuid>0564add3-5776-4b00-995a-1c4ede7ee512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[2]/preceding::div[24]</value>
      <webElementGuid>54e19fb9-b30d-4bd0-bf2c-ac1bb1e0b19a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[6]/div/div/div/div/div[2]/table/tbody/tr[3]/td[5]/div</value>
      <webElementGuid>49706e90-4d87-48af-8938-529d1761e294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '15' or . = '15')]</value>
      <webElementGuid>a490b962-f8f4-4b95-99c9-185d5a8d6327</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
