<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_date_range</name>
   <tag></tag>
   <elementGuidId>067fb2ad-49b7-4807-8b99-c3ed947ec8ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.material-icons.date-picker-open-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='employement_details_tab']/form/div/oxd-decorator/div/div/div[2]/div/div/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;date_range&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3b4d2381-8ad3-470a-8ae3-375a914931aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons date-picker-open-icon</value>
      <webElementGuid>67261479-a813-41f0-bb77-46bb94dd39e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>date_range</value>
      <webElementGuid>6bf2ed74-7c53-4be4-b482-a4d77931472f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employement_details_tab&quot;)/form[@class=&quot;with-standard-section-attached ng-pristine ng-valid ng-valid-schema-form ng-valid-pattern ng-valid-display-input-validity ng-valid-date-range ng-valid-maxlength&quot;]/div[1]/oxd-decorator[1]/div[@class=&quot;form-row&quot;]/div[@class=&quot;form-group col-4&quot;]/div[@class=&quot;input-group form-date ng-pristine ng-valid ng-valid-pattern ng-valid-display-input-validity ng-valid-schema-form ng-valid-date-range&quot;]/div[@class=&quot;input-group-append-container&quot;]/div[@class=&quot;input-group-append&quot;]/button[@class=&quot;btn date-picker-button&quot;]/i[@class=&quot;material-icons date-picker-open-icon&quot;]</value>
      <webElementGuid>ff6b0614-4a8d-4871-8100-e24120548558</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='employement_details_tab']/form/div/oxd-decorator/div/div/div[2]/div/div/button/i</value>
      <webElementGuid>98ad48bd-9945-4428-b9d5-d0c4c4b546da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Probation End Date'])[2]/following::i[1]</value>
      <webElementGuid>f64a1fbb-c9e6-4493-b146-1a83a9301061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Probation End Date'])[1]/following::i[1]</value>
      <webElementGuid>4f4cfac9-92cf-419e-a7d7-69c35779f4c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expected format: yyyy-mm-dd'])[1]/preceding::i[1]</value>
      <webElementGuid>afcf912a-9bf9-4e4f-9706-5dbbd6bc4bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Required'])[1]/preceding::i[1]</value>
      <webElementGuid>feb9b163-939a-49aa-b6ef-cb4dcff0b897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='date_range']/parent::*</value>
      <webElementGuid>6c6577dd-75a8-4add-bb1b-79fdc996a1f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/i</value>
      <webElementGuid>1f99cff6-4a64-40da-be20-749dc7320106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'date_range' or . = 'date_range')]</value>
      <webElementGuid>5c1fd1e9-3882-4f1c-b2f7-c9aa1ba1ce9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
