<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_date_range</name>
   <tag></tag>
   <elementGuidId>067fb2ad-49b7-4807-8b99-c3ed947ec8ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='employement_details_tab']/form/div/oxd-decorator[6]/div/div/div[2]/div/div/button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>oxd-decorator:nth-of-type(6) > div.form-row > div.form-group.col-4 > div[name=&quot;dateForm&quot;] > div.input-group-append-container > div.input-group-append > button.btn.date-picker-button > i.material-icons.date-picker-open-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;date_range&quot;i] >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a4cc6b00-a5b3-40ed-841f-7b77eca9b6fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons date-picker-open-icon</value>
      <webElementGuid>ec467c69-c467-4d72-abfa-ed50bdf5cd31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>date_range</value>
      <webElementGuid>9b3b81dd-850a-4b06-bda7-7099186a4009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employement_details_tab&quot;)/form[@class=&quot;with-standard-section-attached ng-valid ng-valid-schema-form ng-valid-pattern ng-valid-display-input-validity ng-valid-date-range ng-valid-maxlength ng-dirty ng-valid-parse&quot;]/div[1]/oxd-decorator[6]/div[@class=&quot;form-row&quot;]/div[@class=&quot;form-group col-4&quot;]/div[@class=&quot;input-group form-date ng-pristine ng-valid ng-valid-pattern ng-valid-display-input-validity ng-valid-schema-form ng-valid-date-range&quot;]/div[@class=&quot;input-group-append-container&quot;]/div[@class=&quot;input-group-append&quot;]/button[@class=&quot;btn date-picker-button&quot;]/i[@class=&quot;material-icons date-picker-open-icon&quot;]</value>
      <webElementGuid>3cde4dc2-8588-4890-bb1d-bc3ee4598318</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='employement_details_tab']/form/div/oxd-decorator[6]/div/div/div[2]/div/div/button/i</value>
      <webElementGuid>6f369ad3-63ca-410e-8958-f5005d6be121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contract Start Date'])[2]/following::i[1]</value>
      <webElementGuid>2359908f-57d2-45aa-a797-5fd77ba8fb38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contract Start Date'])[1]/following::i[1]</value>
      <webElementGuid>26c32b0e-ce28-4e8d-b501-e495a301c911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expected format: yyyy-mm-dd'])[3]/preceding::i[1]</value>
      <webElementGuid>9b4709ec-0a5f-4fac-9bf7-181d9ad117ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Required'])[3]/preceding::i[1]</value>
      <webElementGuid>e31302cd-07fa-457b-8476-a3e9cf615824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//oxd-decorator[6]/div/div/div[2]/div/div/button/i</value>
      <webElementGuid>05c8b72c-3c64-49f8-b4e3-b993e3a6a156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'date_range' or . = 'date_range')]</value>
      <webElementGuid>c3964698-ff08-42a8-ab8e-f0ad59db269a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='employement_details_tab']/form/div/oxd-decorator/div/div/div[2]/div/div/button/i</value>
      <webElementGuid>98ad48bd-9945-4428-b9d5-d0c4c4b546da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Probation End Date'])[2]/following::i[1]</value>
      <webElementGuid>f64a1fbb-c9e6-4493-b146-1a83a9301061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Probation End Date'])[1]/following::i[1]</value>
      <webElementGuid>4f4cfac9-92cf-419e-a7d7-69c35779f4c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expected format: yyyy-mm-dd'])[1]/preceding::i[1]</value>
      <webElementGuid>afcf912a-9bf9-4e4f-9706-5dbbd6bc4bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Required'])[1]/preceding::i[1]</value>
      <webElementGuid>feb9b163-939a-49aa-b6ef-cb4dcff0b897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='date_range']/parent::*</value>
      <webElementGuid>6c6577dd-75a8-4add-bb1b-79fdc996a1f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/i</value>
      <webElementGuid>1f99cff6-4a64-40da-be20-749dc7320106</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
