<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Select --Architecture TeamQuality_a60494</name>
   <tag></tag>
   <elementGuidId>d9be5dc7-7574-4a1c-840a-e3f0583e12d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#subunit_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='subunit_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Sub Unit&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1bae8336-4aca-4574-b8c8-08c1a0c7447b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!form.translate</value>
      <webElementGuid>5386562e-3066-4ad7-bbdc-045fd7d8a2ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subunit_id</value>
      <webElementGuid>db9aa7f2-e0f1-490e-96ab-f99d985d7e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>model['subunit_id']</value>
      <webElementGuid>29af4caa-a9b5-45d4-bb9c-dc4ca4a05b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model-options</name>
      <type>Main</type>
      <value>form.ngModelOptions</value>
      <webElementGuid>deeebb6a-e529-439f-8075-af41e7c3fd4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>form.readonly</value>
      <webElementGuid>cd0fde49-df9c-41e5-89e1-47f8b3982a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sf-changed</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>c719633f-cf12-4d08-ae62-824934198303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-dropdown</value>
      <webElementGuid>b5e124bf-bac3-4733-97bd-81930e3d665b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'loader-is-showing' : form.showLoader}</value>
      <webElementGuid>457ea4b0-d9f3-4f0f-95ec-42f67731636e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>schema-validate</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>bd8e9ac7-a449-43ab-980a-6797110209ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>item.value as item.name group by item.group for item in form.titleMap</value>
      <webElementGuid>05eb9c63-6d94-4e91-b96d-70428adb281b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ohrm-make-element-non-pristine</name>
      <type>Main</type>
      <value>form.removePristine</value>
      <webElementGuid>25905190-3ced-4c4d-b2c6-2bdb67cfb95b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>subunit_id</value>
      <webElementGuid>54b02ae3-416f-48b5-95c5-6adb01aca0b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Select --Architecture TeamQuality assurance (QA)EngineeringFinanceSalesHuman ResourcesInformation TechnologyTechnical SupportMarketingProductionCustomer SuccessProduct and Training</value>
      <webElementGuid>dd4994f3-e408-40ac-8283-b0049af78843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subunit_id&quot;)</value>
      <webElementGuid>7068536b-a25f-41db-bdd8-8ed741fe833b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='subunit_id']</value>
      <webElementGuid>0ff5953c-d753-4a90-81c5-f6815b744cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='employement_details_tab']/form/div/oxd-decorator/div/div[8]/div/div/select</value>
      <webElementGuid>d202ef5e-8f52-48cd-9892-31f745ad6177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub Unit'])[1]/following::select[1]</value>
      <webElementGuid>194a0716-6d27-4c08-a5de-80663ce630e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_drop_down'])[4]/following::select[1]</value>
      <webElementGuid>11e4d6c0-1cac-4852-b5fd-198df6b2253f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Select --'])[8]/preceding::select[1]</value>
      <webElementGuid>2b8f622e-4a83-4da0-9757-09d54541ab2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Select --'])[9]/preceding::select[1]</value>
      <webElementGuid>0d89f575-8758-4462-a446-3829fbc2f13f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/select</value>
      <webElementGuid>fc9f9c03-1078-4e58-933a-38a351ea5e44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'subunit_id' and @name = 'subunit_id' and (text() = '-- Select --Architecture TeamQuality assurance (QA)EngineeringFinanceSalesHuman ResourcesInformation TechnologyTechnical SupportMarketingProductionCustomer SuccessProduct and Training' or . = '-- Select --Architecture TeamQuality assurance (QA)EngineeringFinanceSalesHuman ResourcesInformation TechnologyTechnical SupportMarketingProductionCustomer SuccessProduct and Training')]</value>
      <webElementGuid>eef18075-1515-4fd5-9e27-c95a558e0910</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
