<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Select --Art DirectorAssistant Di_9f3082</name>
   <tag></tag>
   <elementGuidId>9a9f11a0-1c58-4d1b-a661-fbdb86b16065</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='job_title_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#job_title_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Job Title&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ef743adb-1f0e-47f6-80c1-d5a5e774fcd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!form.translate</value>
      <webElementGuid>d9520c17-eb9f-46a8-8163-cf82ef5f96a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>job_title_id</value>
      <webElementGuid>d2edeada-605e-434f-b057-95e1b105682b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>model['job_title_id']</value>
      <webElementGuid>f5ea8f60-dcdf-4c65-abfe-e0fe541a5941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model-options</name>
      <type>Main</type>
      <value>form.ngModelOptions</value>
      <webElementGuid>b3cda5a2-d5c3-4dd0-9fb9-47a2259dfdc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>form.readonly</value>
      <webElementGuid>4fb313a9-e302-4547-ba7b-3bdd5c107a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sf-changed</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>397b4f27-8180-4606-8fef-8e90a703f638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-dropdown</value>
      <webElementGuid>071697e4-a3c7-41e4-b364-d9e4496bf16e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'loader-is-showing' : form.showLoader}</value>
      <webElementGuid>8a6c286b-c180-483d-bc05-bbd9c1208ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>schema-validate</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>2b1d7ad1-1679-4739-8ee3-2ff518dc01b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>item.value as item.name group by item.group for item in form.titleMap</value>
      <webElementGuid>87065d14-00f1-4377-a52c-8c98bb238c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ohrm-make-element-non-pristine</name>
      <type>Main</type>
      <value>form.removePristine</value>
      <webElementGuid>87a7bf54-e024-4e11-8543-a5240d631667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>job_title_id</value>
      <webElementGuid>e0415b27-7555-4683-b557-683b79c55eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Select --Art DirectorAssistant Director-Digital MarketingAssistant Director-Regional SalesAssistant Manager - HRAssociate Support EngineerBack End DeveloperBrand ManagerBusiness Development ManagerCCOCEOCFOChief ArchitectCHROCMOComptrollerCOOCROCTOCustomer Success ManagerCustomer Support ExecutiveCustomer Support SpecalistDigital Marketing ManagerEngineer ManagerFinance ManagerFront End DeveloperHR AssistantHR DirectorHR ExecutiveHuman Resources (HR) ManagerIntern - Customer SuccessIntern - HRIntern - MarketingIntern - SalesIntern - Software DeveloperIT ExecutiveIT Technical SupportJunior QA EngineerJunior Software EngineerKey Account ManagerLead QA EngineerLead Technical Support EngineerLearning and Development CoordinatorLearning and Development DirectorLearning and Development ManagerLearning and Development SpecialistLocal Marketing ManagerMarketing ExecutivePrincipal Software EngineerProduction Co-ordinatorProduction ManagerProject ManagerQA EngineerRegional HR ManagerRegional Marketing ManagerRegional Sales DirectorRegional Sales ManagerSales Director - AmericasSales Director - APACSales Director - EuropeSales EngineerSales ExecutiveSales ManagerSales Operations ManagerSenior Brand ManagerSenior Customer Success ManagerSenior Front End DeveloperSenior HR ExecutiveSenior Lead QA EngineerSenior Lead Technical Support EngineerSenior Learning and Development ManagerSenior Manager Talent AcquisitionSenior Manager Technical SupportSenior Manager- Digital MarketingSenior Manager- Regional SalesSenior Marketing ManagerSenior Production ManagerSenior QA EngineerSenior Regional HR ManagerSenior Sales ExecutiveSenior Sales ManagerSenior SEO SpecialistSenior Software Development ManagerSenior Software EngineerSenior Technical Support EngineerSenior Technical Support ManagerSenior Vice President - Human ResourcesSenior Vice President - ProductionSenior Vice President of Talent AcquisitionSenior VP of EngineeringSenior Web DeveloperSEO ManagerSEO SpecialistSoftware ArchitectSoftware Development ManagerSoftware EngineerTalent Acquisition ManagerTechnical Support EngineerTechnical Support ManagerVice President - Human ResourcesVice President - ProductionVice President - Talent AcquisitionVice President of EngineeringVice President of Learning and Development</value>
      <webElementGuid>46496994-c77f-4f0e-90e9-7a4271abc18e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;job_title_id&quot;)</value>
      <webElementGuid>e25c21d3-d5b6-45c0-a850-777ba74ff476</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='job_title_id']</value>
      <webElementGuid>aa9f9a2c-979a-4028-b9bf-dd6de1c44ca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='employement_details_tab']/form/div/oxd-decorator/div/div[3]/div/div/select</value>
      <webElementGuid>b00c8f22-aa81-4840-b383-c05f7d878322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job Title'])[1]/following::select[1]</value>
      <webElementGuid>bf801faf-864b-4575-9fd7-148ccef64827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[2]/following::select[1]</value>
      <webElementGuid>0e568be8-537c-4073-82ec-5e6363e77a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Select --'])[2]/preceding::select[1]</value>
      <webElementGuid>21f50014-c545-4208-bae1-e786a2aae8cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Select --'])[3]/preceding::select[1]</value>
      <webElementGuid>b75c97d6-0637-42ef-b147-1bf914819ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/select</value>
      <webElementGuid>f415fc0f-6ecc-43b1-9be4-3b009afea241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'job_title_id' and @name = 'job_title_id' and (text() = '-- Select --Art DirectorAssistant Director-Digital MarketingAssistant Director-Regional SalesAssistant Manager - HRAssociate Support EngineerBack End DeveloperBrand ManagerBusiness Development ManagerCCOCEOCFOChief ArchitectCHROCMOComptrollerCOOCROCTOCustomer Success ManagerCustomer Support ExecutiveCustomer Support SpecalistDigital Marketing ManagerEngineer ManagerFinance ManagerFront End DeveloperHR AssistantHR DirectorHR ExecutiveHuman Resources (HR) ManagerIntern - Customer SuccessIntern - HRIntern - MarketingIntern - SalesIntern - Software DeveloperIT ExecutiveIT Technical SupportJunior QA EngineerJunior Software EngineerKey Account ManagerLead QA EngineerLead Technical Support EngineerLearning and Development CoordinatorLearning and Development DirectorLearning and Development ManagerLearning and Development SpecialistLocal Marketing ManagerMarketing ExecutivePrincipal Software EngineerProduction Co-ordinatorProduction ManagerProject ManagerQA EngineerRegional HR ManagerRegional Marketing ManagerRegional Sales DirectorRegional Sales ManagerSales Director - AmericasSales Director - APACSales Director - EuropeSales EngineerSales ExecutiveSales ManagerSales Operations ManagerSenior Brand ManagerSenior Customer Success ManagerSenior Front End DeveloperSenior HR ExecutiveSenior Lead QA EngineerSenior Lead Technical Support EngineerSenior Learning and Development ManagerSenior Manager Talent AcquisitionSenior Manager Technical SupportSenior Manager- Digital MarketingSenior Manager- Regional SalesSenior Marketing ManagerSenior Production ManagerSenior QA EngineerSenior Regional HR ManagerSenior Sales ExecutiveSenior Sales ManagerSenior SEO SpecialistSenior Software Development ManagerSenior Software EngineerSenior Technical Support EngineerSenior Technical Support ManagerSenior Vice President - Human ResourcesSenior Vice President - ProductionSenior Vice President of Talent AcquisitionSenior VP of EngineeringSenior Web DeveloperSEO ManagerSEO SpecialistSoftware ArchitectSoftware Development ManagerSoftware EngineerTalent Acquisition ManagerTechnical Support EngineerTechnical Support ManagerVice President - Human ResourcesVice President - ProductionVice President - Talent AcquisitionVice President of EngineeringVice President of Learning and Development' or . = '-- Select --Art DirectorAssistant Director-Digital MarketingAssistant Director-Regional SalesAssistant Manager - HRAssociate Support EngineerBack End DeveloperBrand ManagerBusiness Development ManagerCCOCEOCFOChief ArchitectCHROCMOComptrollerCOOCROCTOCustomer Success ManagerCustomer Support ExecutiveCustomer Support SpecalistDigital Marketing ManagerEngineer ManagerFinance ManagerFront End DeveloperHR AssistantHR DirectorHR ExecutiveHuman Resources (HR) ManagerIntern - Customer SuccessIntern - HRIntern - MarketingIntern - SalesIntern - Software DeveloperIT ExecutiveIT Technical SupportJunior QA EngineerJunior Software EngineerKey Account ManagerLead QA EngineerLead Technical Support EngineerLearning and Development CoordinatorLearning and Development DirectorLearning and Development ManagerLearning and Development SpecialistLocal Marketing ManagerMarketing ExecutivePrincipal Software EngineerProduction Co-ordinatorProduction ManagerProject ManagerQA EngineerRegional HR ManagerRegional Marketing ManagerRegional Sales DirectorRegional Sales ManagerSales Director - AmericasSales Director - APACSales Director - EuropeSales EngineerSales ExecutiveSales ManagerSales Operations ManagerSenior Brand ManagerSenior Customer Success ManagerSenior Front End DeveloperSenior HR ExecutiveSenior Lead QA EngineerSenior Lead Technical Support EngineerSenior Learning and Development ManagerSenior Manager Talent AcquisitionSenior Manager Technical SupportSenior Manager- Digital MarketingSenior Manager- Regional SalesSenior Marketing ManagerSenior Production ManagerSenior QA EngineerSenior Regional HR ManagerSenior Sales ExecutiveSenior Sales ManagerSenior SEO SpecialistSenior Software Development ManagerSenior Software EngineerSenior Technical Support EngineerSenior Technical Support ManagerSenior Vice President - Human ResourcesSenior Vice President - ProductionSenior Vice President of Talent AcquisitionSenior VP of EngineeringSenior Web DeveloperSEO ManagerSEO SpecialistSoftware ArchitectSoftware Development ManagerSoftware EngineerTalent Acquisition ManagerTechnical Support EngineerTechnical Support ManagerVice President - Human ResourcesVice President - ProductionVice President - Talent AcquisitionVice President of EngineeringVice President of Learning and Development')]</value>
      <webElementGuid>b646e654-7e67-4170-bb5b-cab23f05c8df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
