<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Select --Craft WorkersLaborers an_89e419</name>
   <tag></tag>
   <elementGuidId>4d64cd80-41c6-4319-837e-582feaffbacd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#job_category_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='job_category_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Job Category&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d5204c23-bc27-4f5d-80a0-04d4f8b191dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!form.translate</value>
      <webElementGuid>d6878178-5ea4-4a62-aac5-1e80b8665520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>job_category_id</value>
      <webElementGuid>8af31bc9-51b0-4487-8d43-1ddcb5a510e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>model['job_category_id']</value>
      <webElementGuid>6761f6a6-d731-4b08-a1ba-b1e1fca1d370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model-options</name>
      <type>Main</type>
      <value>form.ngModelOptions</value>
      <webElementGuid>87676f21-65fa-4706-a767-410f7a696374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>form.readonly</value>
      <webElementGuid>c34cdd8d-8c6e-4f79-80c3-e055900efa23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sf-changed</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>3adf8387-5173-4564-9e53-871a41346a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-dropdown</value>
      <webElementGuid>348fcc98-c50a-434d-9b77-8ed56f8d9f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'loader-is-showing' : form.showLoader}</value>
      <webElementGuid>1ee6c9b7-4e38-49c9-9a19-bac9e6516906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>schema-validate</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>8fc5569e-1951-4e89-809f-191be92a81e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>item.value as item.name group by item.group for item in form.titleMap</value>
      <webElementGuid>c0064faa-6d0d-4948-9d83-766f2fa312d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ohrm-make-element-non-pristine</name>
      <type>Main</type>
      <value>form.removePristine</value>
      <webElementGuid>96dc20dd-64ea-479c-9571-a7002ee35094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>job_category_id</value>
      <webElementGuid>158b3f92-178e-4cbd-9e01-81e5caabf34f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Select --Craft WorkersLaborers and HelpersOffice and Clerical WorkersOfficials and ManagersOperativesProfessionalsSales WorkersService WorkersTechnicians</value>
      <webElementGuid>521510e3-ecf1-4d1c-a2ef-b4bb9394a4c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;job_category_id&quot;)</value>
      <webElementGuid>eb7ac83e-34c4-4ce2-bb13-d5a0860c530f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='job_category_id']</value>
      <webElementGuid>53e94503-7e62-4ead-9ae2-a8b3bef60a71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='employement_details_tab']/form/div/oxd-decorator/div/div[6]/div/div/select</value>
      <webElementGuid>a8542ef6-1c8d-4e99-bbdb-660ec7d5fe06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job Category'])[1]/following::select[1]</value>
      <webElementGuid>ebca3671-fcc5-43bc-89b1-9f788e4ee3d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='file_downloadng'])[1]/following::select[1]</value>
      <webElementGuid>499ef647-ce61-458e-baf3-b907f834124f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Select --'])[6]/preceding::select[1]</value>
      <webElementGuid>ce685431-ce40-43fb-8cb7-3726b57681fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Select --'])[7]/preceding::select[1]</value>
      <webElementGuid>800e78ea-9136-477a-83a3-fb33fed2beb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/select</value>
      <webElementGuid>0fd09a2b-1634-45db-814d-f9f36e9910eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'job_category_id' and @name = 'job_category_id' and (text() = '-- Select --Craft WorkersLaborers and HelpersOffice and Clerical WorkersOfficials and ManagersOperativesProfessionalsSales WorkersService WorkersTechnicians' or . = '-- Select --Craft WorkersLaborers and HelpersOffice and Clerical WorkersOfficials and ManagersOperativesProfessionalsSales WorkersService WorkersTechnicians')]</value>
      <webElementGuid>097d1e0a-b0cc-45bd-a546-b7f53e8a473a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
