<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Select --Architecture TeamQuality_a60494</name>
   <tag></tag>
   <elementGuidId>d9be5dc7-7574-4a1c-840a-e3f0583e12d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='subunit_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#subunit_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Sub Unit&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c8e431df-b7f0-4f83-a27b-0d38ac681632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!form.translate</value>
      <webElementGuid>d355632f-df2f-44d5-9157-11989e891cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subunit_id</value>
      <webElementGuid>493f80e6-c67e-462b-8072-c670a22134e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>model['subunit_id']</value>
      <webElementGuid>2d234052-65f3-4bdb-bf89-c863d1e1b1d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model-options</name>
      <type>Main</type>
      <value>form.ngModelOptions</value>
      <webElementGuid>4a00511a-bbe1-4255-8d2c-4c87b9d71216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>form.readonly</value>
      <webElementGuid>3148f449-73bf-473e-92a7-9d05703d71a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sf-changed</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>c39be856-d721-4f50-a949-9d6f5b44abcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-dropdown</value>
      <webElementGuid>1b531f0c-ef34-4a4d-a873-b2351845fc05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'loader-is-showing' : form.showLoader}</value>
      <webElementGuid>63d58c63-21bd-42de-8751-11112253e733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>schema-validate</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>d131e142-0616-421d-adbb-b942776b0d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>item.value as item.name group by item.group for item in form.titleMap</value>
      <webElementGuid>2e7ea320-f0e1-433f-9fff-ac1dfd7d00be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ohrm-make-element-non-pristine</name>
      <type>Main</type>
      <value>form.removePristine</value>
      <webElementGuid>113df61d-6c73-425d-99dc-0e086d3938bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>subunit_id</value>
      <webElementGuid>537a6380-be86-4505-98a6-2c649a94f369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Select --Architecture TeamQuality assurance (QA)EngineeringFinanceSalesHuman ResourcesInformation TechnologyTechnical SupportMarketingProductionCustomer SuccessProduct and Training</value>
      <webElementGuid>cbd27046-6523-4c5a-92c2-84fa881ffa08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subunit_id&quot;)</value>
      <webElementGuid>296ff4d6-b7c5-43e0-a376-756e81d9da19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='subunit_id']</value>
      <webElementGuid>96cb4ca7-6cc1-42e1-a29f-2b242e126223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='employement_details_tab']/form/div/oxd-decorator/div/div[8]/div/div/select</value>
      <webElementGuid>9b249c8e-c699-4631-9595-7842438d1972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub Unit'])[1]/following::select[1]</value>
      <webElementGuid>e130d1f7-4d16-476d-9ed4-081f77f53d34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_drop_down'])[4]/following::select[1]</value>
      <webElementGuid>58aadeee-e16d-4db4-9c33-ff2de75a7775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Select --'])[10]/preceding::select[1]</value>
      <webElementGuid>dc3d1ae8-f019-4044-8bc4-8a82b81ed80f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Select --'])[11]/preceding::select[1]</value>
      <webElementGuid>a433b228-16a2-4e35-9a07-0e5e845d8843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/select</value>
      <webElementGuid>09fa19b1-b580-4e76-bc6b-d29b7d367a03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'subunit_id' and @name = 'subunit_id' and (text() = '-- Select --Architecture TeamQuality assurance (QA)EngineeringFinanceSalesHuman ResourcesInformation TechnologyTechnical SupportMarketingProductionCustomer SuccessProduct and Training' or . = '-- Select --Architecture TeamQuality assurance (QA)EngineeringFinanceSalesHuman ResourcesInformation TechnologyTechnical SupportMarketingProductionCustomer SuccessProduct and Training')]</value>
      <webElementGuid>871b5d9a-4e3e-483c-8ca0-472bccbbb048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Select --'])[8]/preceding::select[1]</value>
      <webElementGuid>2b8f622e-4a83-4da0-9757-09d54541ab2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Select --'])[9]/preceding::select[1]</value>
      <webElementGuid>0d89f575-8758-4462-a446-3829fbc2f13f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
