<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Select --FreelanceFull-Time Contr_ec654f</name>
   <tag></tag>
   <elementGuidId>28dd1c1b-31b6-4a8d-b3fa-199304001d26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#employment_status_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='employment_status_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Employment Status&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ae86b5e7-e264-4815-babf-cde04a157024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!form.translate</value>
      <webElementGuid>1923d399-be81-4a6d-8dad-a06a005244f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>employment_status_id</value>
      <webElementGuid>cb202ff4-dd3c-49fa-b4aa-73c6a9cd47ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>model['employment_status_id']</value>
      <webElementGuid>c3714fd1-8994-47cb-9392-498e93b36bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model-options</name>
      <type>Main</type>
      <value>form.ngModelOptions</value>
      <webElementGuid>e10f7f08-3dbe-4e1e-90c3-aebc1a5629b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>form.readonly</value>
      <webElementGuid>8723bb5b-ecb2-4ba9-9eb4-254f70840701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sf-changed</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>563cb000-2be0-4439-b962-20bdc76594d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-dropdown</value>
      <webElementGuid>17161f80-0df5-4061-9b5f-6eec017a783e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'loader-is-showing' : form.showLoader}</value>
      <webElementGuid>41869b96-72ee-4e47-bc76-22d5017d5d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>schema-validate</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>d52558b4-3e25-451a-8b26-1592cd51fc3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>item.value as item.name group by item.group for item in form.titleMap</value>
      <webElementGuid>a31c6546-bdc7-4cad-9758-279b0f4f41bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ohrm-make-element-non-pristine</name>
      <type>Main</type>
      <value>form.removePristine</value>
      <webElementGuid>a73045e0-391a-48df-8888-2fe6c4a6ba03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>employment_status_id</value>
      <webElementGuid>8ce3feb9-4cb5-4e1c-8d40-cc5ee4415e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Select --FreelanceFull-Time ContractFull-Time InternshipFull-Time PermanentFull-Time ProbationPart-Time ContractPart-Time InternshipPart-Time PermanentPart-Time Regular</value>
      <webElementGuid>f3838db7-7d8e-4ffd-9a1a-2160c1ec9cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employment_status_id&quot;)</value>
      <webElementGuid>64a90c1d-5615-4017-8619-9f7cd4b8a189</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='employment_status_id']</value>
      <webElementGuid>eca34705-aa81-48b7-b0eb-582d2047b525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='employement_details_tab']/form/div/oxd-decorator/div/div[4]/div/div/select</value>
      <webElementGuid>e51f0074-c455-4d05-bffb-255b8bdac8c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employment Status'])[1]/following::select[1]</value>
      <webElementGuid>266c87f2-18d2-4150-bbc5-524d7e2854b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_drop_down'])[2]/following::select[1]</value>
      <webElementGuid>a78da998-0667-4238-973e-38e41176377a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Select --'])[4]/preceding::select[1]</value>
      <webElementGuid>6fca7080-808f-4117-b308-cafe4343d25b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Select --'])[5]/preceding::select[1]</value>
      <webElementGuid>deb09c82-0e9c-4cda-8e47-13c42b5135fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/select</value>
      <webElementGuid>b06fb2e7-25fc-4f8d-9ac6-13c68bb98636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'employment_status_id' and @name = 'employment_status_id' and (text() = '-- Select --FreelanceFull-Time ContractFull-Time InternshipFull-Time PermanentFull-Time ProbationPart-Time ContractPart-Time InternshipPart-Time PermanentPart-Time Regular' or . = '-- Select --FreelanceFull-Time ContractFull-Time InternshipFull-Time PermanentFull-Time ProbationPart-Time ContractPart-Time InternshipPart-Time PermanentPart-Time Regular')]</value>
      <webElementGuid>04dfe14d-f16e-4302-b04b-47f59026a71a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
