<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Freelance</name>
   <tag></tag>
   <elementGuidId>44c2eb03-bfc4-4580-ae08-1628c8f05d23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bs-select-3-1 > span.text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bs-select-3-1']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#bs-select-3-1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>230a80d0-0da8-4bc5-95af-57dbb00afd80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b3e32762-80fc-48dc-9402-705390240a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Freelance</value>
      <webElementGuid>72695cf5-3fdf-48d3-90d3-b5079863f4d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-3-1&quot;)/span[@class=&quot;text&quot;]</value>
      <webElementGuid>cb957ca8-ccfb-4b4c-8d6c-ff68c7b06e57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='bs-select-3-1']/span</value>
      <webElementGuid>c3f534d3-5b64-4bed-8b86-68ec8d7cf241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Select --'])[5]/following::span[1]</value>
      <webElementGuid>df0270c7-c9aa-4359-ab46-664c7d575b3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Select --'])[4]/following::span[2]</value>
      <webElementGuid>85a3fe85-05d4-4669-b1cf-ead4895f4368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full-Time Contract'])[2]/preceding::span[1]</value>
      <webElementGuid>41c5297b-bde1-464e-ba4b-22880743ced4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full-Time Internship'])[2]/preceding::span[2]</value>
      <webElementGuid>92fe0e69-1faa-4ea8-867e-2e7394816ee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/ul/li[2]/a/span</value>
      <webElementGuid>f17e8e6f-72b5-4e31-883f-4f4fb46b9933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Freelance' or . = 'Freelance')]</value>
      <webElementGuid>eb303b82-a135-4744-8b0d-15ee25459417</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
