<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Art Director</name>
   <tag></tag>
   <elementGuidId>556a6b4e-3a24-44b1-a58a-889153508007</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bs-select-2-1 > span.text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bs-select-2-1']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#bs-select-2-1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>18a7d47a-8982-473e-8fad-4b9344c133ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ef95b0b9-2a0f-440e-acec-dbcc8cdbb52b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Art Director</value>
      <webElementGuid>53e9e207-084a-4855-80ac-0ee1db17145f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-2-1&quot;)/span[@class=&quot;text&quot;]</value>
      <webElementGuid>9ba155dc-6628-4fbc-889e-ba81f171681b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='bs-select-2-1']/span</value>
      <webElementGuid>972caedc-d968-4ff4-aa2c-1818da7c7791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Select --'])[3]/following::span[1]</value>
      <webElementGuid>9589587e-d211-4170-bb67-f8f17c6a1f0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Select --'])[2]/following::span[2]</value>
      <webElementGuid>1a1098d2-8606-432f-87b7-d23571202640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assistant Director-Digital Marketing'])[2]/preceding::span[1]</value>
      <webElementGuid>b273f110-b761-424b-801b-1b5ee2e7bf7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assistant Director-Regional Sales'])[2]/preceding::span[2]</value>
      <webElementGuid>a0e3b115-311f-41e2-b5f8-f1f26cf7ffcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/ul/li[2]/a/span</value>
      <webElementGuid>5edcdb78-839e-44c0-b4a1-ccca5410fc81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Art Director' or . = 'Art Director')]</value>
      <webElementGuid>a6b7a1ac-b1a8-4785-b1b6-f0f2d5474665</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
