<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_oxd_home_menu</name>
   <tag></tag>
   <elementGuidId>61896d17-04a0-4775-b152-f2957946585f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.tooltipped > i.material-icons</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='top-ribbon-menu']/div/div/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;oxd_home_menu&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d0f7bb78-4171-4d1f-895e-50456e43520c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons</value>
      <webElementGuid>69ca774e-2b43-4909-ae1e-0565f39b422c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>oxd_home_menu</value>
      <webElementGuid>bce006b8-a3d3-4700-a014-9f6e0ea58e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-ribbon-menu&quot;)/div[@class=&quot;top-ribbon-menu-basic-navigation menu-separator&quot;]/div[@class=&quot;basic-navigation&quot;]/a[@class=&quot;tooltipped&quot;]/i[@class=&quot;material-icons&quot;]</value>
      <webElementGuid>cd292299-748a-4652-90db-9d3bdbbc93c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top-ribbon-menu']/div/div/a/i</value>
      <webElementGuid>c8d8c524-376f-4547-b496-28c3e83b83ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout from all browsers'])[1]/following::i[1]</value>
      <webElementGuid>9d0779ae-061b-46e4-ab94-b858ea093e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_drop_down'])[1]/following::i[1]</value>
      <webElementGuid>16957281-fcd3-44fe-9f38-e4e3386f618f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::i[1]</value>
      <webElementGuid>8520f419-e746-4dc4-ae0a-c5a2a8a4152a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_back'])[1]/preceding::i[1]</value>
      <webElementGuid>41576a43-981a-4fc1-8fe9-38390d5ca9f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='oxd_home_menu']/parent::*</value>
      <webElementGuid>f77f8d01-b6d0-426d-9705-6b8c405da616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//top-menu/div/div/div/div/a/i</value>
      <webElementGuid>aeb9c01d-ccdb-4861-8216-612fc32b3e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'oxd_home_menu' or . = 'oxd_home_menu')]</value>
      <webElementGuid>9984263d-5538-4424-8552-1699ee5324e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
