<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-- Select --</name>
   <tag></tag>
   <elementGuidId>27cd0ff7-012d-43e8-ab61-e7c6a83661af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='select-options-76992772-bdd0-b764-c953-2886511f3e6d']/li/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.selected > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#select-options-76992772-bdd0-b764-c953-2886511f3e6d >> internal:text=&quot;-- Select --&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9e46e493-00a0-4154-a16b-9f25503ecb22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Select --</value>
      <webElementGuid>5d47631f-c05e-4756-b40a-d3942ea33147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-options-76992772-bdd0-b764-c953-2886511f3e6d&quot;)/li[@class=&quot;selected&quot;]/span[1]</value>
      <webElementGuid>01d0d4d3-627c-49ff-a547-e065c13183f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select-options-76992772-bdd0-b764-c953-2886511f3e6d']/li/span</value>
      <webElementGuid>15b6c7e2-113c-46b0-9b7a-b386e1e084d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='▼'])[1]/following::span[1]</value>
      <webElementGuid>03c4bfb7-6611-4a24-a048-dfe54ba2cb27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Onboarding'])[3]/following::span[2]</value>
      <webElementGuid>88c9c5bb-5951-4c2e-ba26-92e530380e7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Onboarding - India'])[1]/preceding::span[1]</value>
      <webElementGuid>119e735a-a8aa-4f36-ad9d-3a3190fa4015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Onboarding - India'])[2]/preceding::span[2]</value>
      <webElementGuid>7db89095-b5ab-468d-88a2-b13c528de1dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='-- Select --']/parent::*</value>
      <webElementGuid>2942ef34-fa79-4823-bb3e-047ddee50b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//sf-decorator/div/div/ul/li/span</value>
      <webElementGuid>dfb81ca5-c89e-486d-a70b-124d78e610ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '-- Select --' or . = '-- Select --')]</value>
      <webElementGuid>790eeba3-42ec-4207-aad9-5ff2f16467b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select-options-dd53c833-a5e5-4886-c023-46d94d2d5cce']/li/span</value>
      <webElementGuid>1ab9774c-7ea8-480c-b305-0d8173034177</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
