<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Onboarding - USA</name>
   <tag></tag>
   <elementGuidId>8bdd0f90-0126-4f9c-8874-8e45b84ed9a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='select-options-76992772-bdd0-b764-c953-2886511f3e6d']/li[4]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(4) > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#select-options-76992772-bdd0-b764-c953-2886511f3e6d >> internal:text=&quot;Onboarding - USA&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e9e8c230-1ecf-42a5-ba5d-e1ff7c733f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Onboarding - USA</value>
      <webElementGuid>67a80173-09d2-4dd5-82c7-e23b5953fd63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-options-76992772-bdd0-b764-c953-2886511f3e6d&quot;)/li[4]/span[1]</value>
      <webElementGuid>180c6e81-a630-4e87-86a8-21ff25897db8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select-options-76992772-bdd0-b764-c953-2886511f3e6d']/li[4]/span</value>
      <webElementGuid>caa0e215-c452-4241-9941-bac02fdf821d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Onboarding - India'])[2]/following::span[1]</value>
      <webElementGuid>fb21a2e7-6cb3-4391-8f17-d6779c4913e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Onboarding - India'])[1]/following::span[2]</value>
      <webElementGuid>b89dc09e-258b-45ff-935b-6c5b49b07560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Onboarding - South Africa'])[1]/preceding::span[1]</value>
      <webElementGuid>2d17de41-e58e-46d2-bf72-3e53fc182981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event Template'])[1]/preceding::span[2]</value>
      <webElementGuid>35089c69-6938-47ed-98b6-f0a96232a9fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Onboarding - USA']/parent::*</value>
      <webElementGuid>be0c2f67-bb8b-424a-97c2-f396d109ebcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/span</value>
      <webElementGuid>0478980f-1ef8-4c73-9d14-928a51a4aed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Onboarding - USA' or . = 'Onboarding - USA')]</value>
      <webElementGuid>3618db17-d620-4cea-a119-014270238eba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select-options-dd53c833-a5e5-4886-c023-46d94d2d5cce']/li[4]/span</value>
      <webElementGuid>ece92300-10bb-458e-9557-f3bf95b1c6e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
