<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Emergency Contacts</name>
   <tag></tag>
   <elementGuidId>ca083820-eabd-4479-aa70-a2df100c161b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topbar-ribbon']/div[2]/ui-view/div/div[2]/top-level-menu-item/div/sub-menu-container/div/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>sub-menu-container >> internal:role=link[name=&quot;Emergency Contacts&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7bfcdcfa-9a1c-4e14-80f8-2adb9c9a0924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!!menu.uiSref &amp;&amp; maxLevels > 0</value>
      <webElementGuid>4892fa9a-98f4-466d-a6f6-f115f86f18be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-focus</name>
      <type>Main</type>
      <value>showSubmenu($index)</value>
      <webElementGuid>5575cbfa-b8d5-4463-b30f-9b0ff91a8141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-mouseover</name>
      <type>Main</type>
      <value>showSubmenu($index)</value>
      <webElementGuid>92b35efe-0854-47fc-a8e5-e4cfe775c139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub-menu-item-link truncate</value>
      <webElementGuid>8b324f52-2b06-47c0-b81a-c12b08c498f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ui-sref</name>
      <type>Main</type>
      <value>pim.employees.profile.emergency_contact</value>
      <webElementGuid>7556867c-7b86-4b14-a0a5-ecfd27f48b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ui-sref-active</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>0cd96ed9-1744-4bf8-af7a-d6119de0ee51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-target</name>
      <type>Main</type>
      <value>{{menu.target}}</value>
      <webElementGuid>acbffccf-2b1d-40dc-8ec1-8b4b552ff976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>menu_employee_profile_EmergencyContacts</value>
      <webElementGuid>4d58c5c8-ee98-4827-9296-64299c19e25a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>da4821fd-90c7-4463-8582-f06f414b8c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/pim/employees/204/emergency_contact</value>
      <webElementGuid>8313daa3-2b35-4d6e-ac00-fc6d8fdb4c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Emergency Contacts </value>
      <webElementGuid>71c3560f-d439-4bbe-b3a0-6407c1183976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topbar-ribbon&quot;)/div[@class=&quot;custom-top-ribbon&quot;]/ui-view[1]/div[@class=&quot;employee-profile-custom-top-ribbon custom-ribbon-with-menu-and-more-menu more-menu-with-vertical-scrollbar&quot;]/div[@class=&quot;more-menu&quot;]/top-level-menu-item[1]/div[@class=&quot;top-level-menu-item-container&quot;]/sub-menu-container[@class=&quot;level-1-sub-menu opened&quot;]/div[@class=&quot;sub-menu-container&quot;]/div[@class=&quot;sub-menu-item&quot;]/a[@class=&quot;sub-menu-item-link truncate&quot;]</value>
      <webElementGuid>d683eb9e-a9fe-4372-9ce7-8e658fdccdce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topbar-ribbon']/div[2]/ui-view/div/div[2]/top-level-menu-item/div/sub-menu-container/div/div[3]/a</value>
      <webElementGuid>af53b3d7-4b10-4b0a-b693-5f830fb8a61b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Emergency Contacts')])[2]</value>
      <webElementGuid>9493bf55-ea02-4b9d-ba7f-ce17e3db87e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Details'])[2]/following::a[1]</value>
      <webElementGuid>7e69d50a-f33b-4b8f-a1ad-135108ed8987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal Details'])[2]/following::a[2]</value>
      <webElementGuid>006e175e-eb4e-4169-b6f8-04735b585898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dependents'])[2]/preceding::a[1]</value>
      <webElementGuid>d25ed2c4-062e-406f-b982-f7162aebf25c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Immigration'])[2]/preceding::a[2]</value>
      <webElementGuid>a888d0bc-d901-4d74-b224-6dbfdbd854cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#/pim/employees/204/emergency_contact')])[2]</value>
      <webElementGuid>92f77e6f-917e-4748-835d-91585ff95149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//sub-menu-container/div/div[3]/a</value>
      <webElementGuid>5cfc056d-3915-4404-be1c-db3d1d7a5e5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/pim/employees/204/emergency_contact' and (text() = ' Emergency Contacts ' or . = ' Emergency Contacts ')]</value>
      <webElementGuid>2cb4a218-a212-4063-a8e9-e5e1feb28332</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
