<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_add</name>
   <tag></tag>
   <elementGuidId>9058af25-d0e0-421e-86cb-18c3dcc6ec40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.fixed-action-btn.floating-add-btn.tooltipped.active > a.btn-floating.btn-large.waves-effect.waves-light > i.material-icons</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='socialMediaDiv']/div/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#socialMediaDiv a >> internal:has-text=&quot;add&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>1faf55f9-ec9e-4705-b0d1-679866cb19c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons</value>
      <webElementGuid>f6ccc245-94d4-490e-994b-6e6ec81a1c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>add</value>
      <webElementGuid>3355406c-30ea-4fef-9ea9-3514ac343d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;socialMediaDiv&quot;)/div[@class=&quot;fixed-action-btn floating-add-btn tooltipped active&quot;]/a[@class=&quot;btn-floating btn-large waves-effect waves-light&quot;]/i[@class=&quot;material-icons&quot;]</value>
      <webElementGuid>4a7f6f75-e03b-4b11-af4f-3a3b835f6c8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='socialMediaDiv']/div/a/i</value>
      <webElementGuid>ea75f2f6-a03f-408b-b54c-52e80c670b74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Telephone'])[1]/following::i[1]</value>
      <webElementGuid>2790fca8-a5a3-40de-8dab-d61cb53f425c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile'])[1]/following::i[1]</value>
      <webElementGuid>69b26273-a602-4e1f-9d96-a7938ece7285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Emergency Contact'])[1]/preceding::i[1]</value>
      <webElementGuid>ab34c659-4a7c-43ec-afcf-145ef3241ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attachments'])[1]/preceding::i[1]</value>
      <webElementGuid>58184772-6668-43f0-bd26-09f04b215be6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a/i</value>
      <webElementGuid>3bdec835-09fa-4c37-a21b-a924cf7e4902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'add' or . = 'add')]</value>
      <webElementGuid>cfb99589-b86d-4134-abc3-2a880364442a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
