<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Home_home_phone</name>
   <tag></tag>
   <elementGuidId>fa1d6394-6b70-4fcf-a37f-6b4e2a844bb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#home_phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='home_phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Home&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef22866a-b33e-4841-ad18-c96090e43209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>home_phone</value>
      <webElementGuid>be5a9551-a006-4d90-8b71-8b369cc52040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sf-changed</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>35bf8d31-8f50-4283-92f7-c467348b0485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid ng-empty ng-valid-phone-number ng-valid-schema-form ng-not-empty-add ng-pristine-remove ng-dirty-add ng-valid-parse-add ng-valid-atleast-one-phone-number-required-add</value>
      <webElementGuid>0a85b796-0b2a-4360-bb5c-077d5f0be086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9657e952-ab65-4d17-a922-004d1092e3c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>form.readonly</value>
      <webElementGuid>c7dd6de5-2f3b-4a5b-a20b-581e7881a876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>schema-validate</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>455dd51a-59a2-4286-a287-37d9f2250129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>model['home_phone']</value>
      <webElementGuid>4fdac78e-4cf3-4c05-bdf5-f2e584048ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model-options</name>
      <type>Main</type>
      <value>form.ngModelOptions</value>
      <webElementGuid>3c6fe8a2-3861-421a-8d9c-5f739fc16211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ohrm-make-element-non-pristine</name>
      <type>Main</type>
      <value>form.removePristine</value>
      <webElementGuid>f5b7f2e7-111e-424d-b76c-7dde5a976e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-autocomplete</name>
      <type>Main</type>
      <value>{{form.autocompleteOff}}</value>
      <webElementGuid>94df0998-88c0-4e4e-8649-7b6f1dfb9835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'has-help-text': !!(form.helpText)}</value>
      <webElementGuid>38df224b-0631-4851-ad36-000462fafe09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-data-help-text-class</name>
      <type>Main</type>
      <value>{{form.helpTextClass}}</value>
      <webElementGuid>f5353051-fc43-492b-ab61-ab26163c388a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home_phone&quot;)</value>
      <webElementGuid>c2dc13bc-a48d-489b-ac0c-32b23b770f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-animate</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>e4729300-47e4-4e7c-b147-d40ee531c964</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='home_phone']</value>
      <webElementGuid>1e0a8980-58fa-4f48-be0a-555fb765b349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-holder']/div/div/div/div[2]/form/oxd-decorator[3]/div/div/div[2]/input</value>
      <webElementGuid>944c3371-b9ea-4241-a884-6c1340413e9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//oxd-decorator[3]/div/div/div[2]/input</value>
      <webElementGuid>340627cd-4447-40bc-b56b-3e6a7b51a27e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'home_phone' and @type = 'text']</value>
      <webElementGuid>3c355b01-11c2-4bc4-b3c6-6ca456444d2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
