<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Attachment size exceeded</name>
   <tag></tag>
   <elementGuidId>050241cd-35c3-48da-8f9c-a0ee7eeb1577</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.help-block.invalid-feedback</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-holder']/div/div/div/div[2]/form/oxd-decorator/div/div/div/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Attachment size exceeded&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d0f37bc9-6e30-439b-a4b8-4bcc7483fd29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>help-block invalid-feedback</value>
      <webElementGuid>1f2347f4-2f3e-4250-949a-db4b81986511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sf-message</name>
      <type>Main</type>
      <value>form.description</value>
      <webElementGuid>30847e75-ae8f-4cbc-9c39-99897fc457dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Attachment size exceeded</value>
      <webElementGuid>5235c801-def5-4912-a017-972e24094e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-holder&quot;)/div[@class=&quot;modal show&quot;]/div[@class=&quot;modal-dialog modal-md&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/form[@class=&quot;generic-oxd-modal-form needs-validation ng-valid-file-type ng-dirty ng-valid-parse ng-invalid ng-invalid-file-size ng-invalid-schema-form&quot;]/oxd-decorator[1]/div[@class=&quot;form-row&quot;]/div[@class=&quot;form-group col-12&quot;]/div[@class=&quot;file-field&quot;]/span[1]/span[@class=&quot;help-block invalid-feedback&quot;]</value>
      <webElementGuid>85629cf7-20fa-41f4-954a-16dbf61c67a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-holder']/div/div/div/div[2]/form/oxd-decorator/div/div/div/span/span</value>
      <webElementGuid>07f81e83-46f0-40d6-99d4-0030b4ee0ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browse'])[1]/following::span[1]</value>
      <webElementGuid>3926f276-931d-492e-a842-8ca60aec5612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Accepts up to 5MB)'])[1]/following::span[2]</value>
      <webElementGuid>628704fc-9a56-40b5-a544-224937b7811f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[2]/preceding::span[1]</value>
      <webElementGuid>187b6671-b592-4c3f-b12c-1f1eb65b9297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='* Required'])[1]/preceding::span[2]</value>
      <webElementGuid>36c31627-4d53-4f62-8112-9e232e97db39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Attachment size exceeded']/parent::*</value>
      <webElementGuid>cb357ae4-d29a-4813-bfbf-7231b69537c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>c80dd530-7a7f-46fc-8709-df24d8dd5ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Attachment size exceeded' or . = 'Attachment size exceeded')]</value>
      <webElementGuid>2e78bf30-e06f-4dfc-9186-cded5f785972</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
