<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Login_icon show-icon</name>
   <tag></tag>
   <elementGuidId>a3c0ed50-4fea-4ee5-ac95-1e98248d598d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmLogin']/div[2]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.icon.show-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Show Password&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>231e7ea8-4363-4d24-9dc3-a9d88e751fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon show-icon</value>
      <webElementGuid>ad9e1adf-94a8-4877-805b-12296b96aa63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Show Password</value>
      <webElementGuid>b93e48c8-2ddb-4976-92aa-ce37b9741cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/webres_65f025a10f6573.94024044/themes/default/images/login/oxd/visibility.svg</value>
      <webElementGuid>c2e96f09-2c34-4ab8-ae1c-e81bef0a8d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmLogin&quot;)/div[@class=&quot;input-field&quot;]/div[@class=&quot;visibility-holder&quot;]/img[@class=&quot;icon show-icon&quot;]</value>
      <webElementGuid>4ae13991-6b4e-432f-a46b-d2723d90bc48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmLogin']/div[2]/div/img</value>
      <webElementGuid>01100391-6d2e-40b3-b4d4-d3d43172eafa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='Show Password']</value>
      <webElementGuid>d6dd59fc-ae47-4d4d-91eb-c9583f7cbf14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img</value>
      <webElementGuid>916ef8b0-aae2-4710-9336-4a3c39581a19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Show Password' and @src = '/webres_65f025a10f6573.94024044/themes/default/images/login/oxd/visibility.svg']</value>
      <webElementGuid>a2d3b1b6-f00c-4f79-9e57-a7f0825ed820</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
