<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_add</name>
   <tag></tag>
   <elementGuidId>7ac8a832-9022-4145-af8f-f1c5b224768a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.fixed-action-btn.floating-add-btn.tooltipped.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='licenseDiv']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^add$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d3f4ef25-5b53-4d96-9957-d6d9e8ec5225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>licenseCtrl.permissions.create</value>
      <webElementGuid>cc7cae4a-7e7c-47db-b20b-884df0eb5478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fixed-action-btn floating-add-btn tooltipped active</value>
      <webElementGuid>78588ef0-3664-4fe1-8580-99a3cd1d4838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip</name>
      <type>Main</type>
      <value>Add License</value>
      <webElementGuid>3a2d6bbe-1d82-416d-9b17-2c935d143c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-position</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>33b881dd-af46-4807-a8ee-fdd21c79cef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-id</name>
      <type>Main</type>
      <value>eef98551-1cbc-708c-a80c-6ff404d812e2</value>
      <webElementGuid>94af7272-58ed-4f33-8073-6ca7017aa5ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>add</value>
      <webElementGuid>1f81feb7-27e2-49ea-9dcf-033b132e27eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;licenseDiv&quot;)/div[@class=&quot;fixed-action-btn floating-add-btn tooltipped active&quot;]</value>
      <webElementGuid>adcec560-8c3f-4c52-9af0-18f8d6dc28d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='licenseDiv']/div</value>
      <webElementGuid>2b08bcc7-ae5d-4cd5-8af4-3e9ac5b77434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='▼'])[1]/following::div[1]</value>
      <webElementGuid>981afd97-b145-4d2a-8e2c-ccb0aa69a1ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rows per page'])[1]/following::div[2]</value>
      <webElementGuid>97b90af2-7576-4c1a-aea9-966b2f4c3515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add License'])[1]/preceding::div[3]</value>
      <webElementGuid>90eeb7a5-f8c6-4037-a2b2-56219e3b7a92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ui-view/div/div/div</value>
      <webElementGuid>ca247604-b34e-42c5-945a-67f1704e00ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'add' or . = 'add')]</value>
      <webElementGuid>5184906d-cba4-4cf5-834a-9556e5c90051</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
