<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_arrow_upward</name>
   <tag></tag>
   <elementGuidId>9e57b76c-7c20-4e1a-ae4f-0c99c2ab7149</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.material-icons.list-sorting-icons.tiny</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='languagesDiv']/crud-panel/div/div/list/table/thead/tr/th[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;arrow_upward&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>aa217a3c-2d63-4942-b7cb-19a928a3dbbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>listField.sortable &amp;&amp; (list.sortField === undefined || list.sortField == listField.name)</value>
      <webElementGuid>706dd16f-1f07-4408-bb01-4dad4e44dad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons list-sorting-icons tiny</value>
      <webElementGuid>54149dca-fc9d-4faf-9bde-0c4301c429bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>arrow_upward</value>
      <webElementGuid>a34f250a-e48e-4fc2-ab32-afeb67767aa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;languagesDiv&quot;)/crud-panel[1]/div[@class=&quot;form-div&quot;]/div[@class=&quot;list-container&quot;]/list[1]/table[@class=&quot;highlight bordered&quot;]/thead[1]/tr[1]/th[@class=&quot;row-name sortable&quot;]/i[@class=&quot;material-icons list-sorting-icons tiny&quot;]</value>
      <webElementGuid>56cd0d66-5857-4ed3-96ee-8a57e32cf0ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='languagesDiv']/crud-panel/div/div/list/table/thead/tr/th[2]/i</value>
      <webElementGuid>5f66756e-8dae-4a11-a981-6a7b8d796e78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[1]/following::i[1]</value>
      <webElementGuid>c6867c13-1920-4b7e-889f-3daf4facf314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cantonese'])[1]/preceding::i[1]</value>
      <webElementGuid>d3fa1384-86db-4f6f-9add-af5a3ee92c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ohrm_edit'])[1]/preceding::i[1]</value>
      <webElementGuid>7d684ec1-7b57-4f41-b2ab-35c1fc96d543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='arrow_upward']/parent::*</value>
      <webElementGuid>63c13140-9efd-4f7d-8efd-ec5dbf17ff5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]/i</value>
      <webElementGuid>81bd9c32-20e5-491b-85c5-8073c2961558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'arrow_upward' or . = 'arrow_upward')]</value>
      <webElementGuid>07f29190-ded3-4ca7-ae56-2138f725c946</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
