<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_arrow_downward</name>
   <tag></tag>
   <elementGuidId>22d921dc-7507-4c1a-a363-b349fa38aad0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.material-icons.list-sorting-icons.tiny</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='languagesDiv']/crud-panel/div/div/list/table/thead/tr/th[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;arrow_downward&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4378e55f-5a3d-4253-9f8c-f8cf79ea9f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>listField.sortable &amp;&amp; (list.sortField === undefined || list.sortField == listField.name)</value>
      <webElementGuid>7264a1ff-41a8-48e5-8f3a-c14f6c01a8eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons list-sorting-icons tiny</value>
      <webElementGuid>168d26c5-7ab1-4528-bdfe-e6c05f482dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>arrow_downward</value>
      <webElementGuid>58cc37c6-86ee-467a-b0d6-ccf407822a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;languagesDiv&quot;)/crud-panel[1]/div[@class=&quot;form-div&quot;]/div[@class=&quot;list-container&quot;]/list[1]/table[@class=&quot;highlight bordered&quot;]/thead[1]/tr[1]/th[@class=&quot;row-name sortable&quot;]/i[@class=&quot;material-icons list-sorting-icons tiny&quot;]</value>
      <webElementGuid>b5f430fc-5931-4fe9-8660-c8ed1afca54e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='languagesDiv']/crud-panel/div/div/list/table/thead/tr/th[2]/i</value>
      <webElementGuid>7e28f264-4d68-4474-a630-6e35c872414a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[1]/following::i[1]</value>
      <webElementGuid>fd3ca4af-7a48-4265-ae8a-abbf536ec349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zulu'])[1]/preceding::i[1]</value>
      <webElementGuid>bb96c85a-23b0-4312-9f13-ce43c63f2e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ohrm_edit'])[1]/preceding::i[1]</value>
      <webElementGuid>e7f58890-8030-40e9-888d-c32d779bec6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='arrow_downward']/parent::*</value>
      <webElementGuid>871c77a2-4c57-47b6-bcf7-35d58f910e1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]/i</value>
      <webElementGuid>988e4ac4-cf1f-4ffd-b948-cf6f594c67d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'arrow_downward' or . = 'arrow_downward')]</value>
      <webElementGuid>1c4558bd-43c0-4897-b4b6-f8edcea6c17e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='licenseDiv']/crud-panel/div/div/list/table/thead/tr/th[2]/i</value>
      <webElementGuid>e0d83998-9786-4c25-a8cd-6849562d49c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Travel Agent License'])[1]/preceding::i[1]</value>
      <webElementGuid>81e370b1-6b47-4388-8246-28dd4d1adb89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
