<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_more_horiz</name>
   <tag></tag>
   <elementGuidId>d63f55e6-a2c4-45b4-a5f4-346a6edf362c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.material-icons.icons-color.orange-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='languagesDiv']/crud-panel/div/div/list/table/thead/tr/th/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;more_horiz&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>da003a31-7869-46e5-98c7-a39599ccd48b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons icons-color orange-text</value>
      <webElementGuid>3484c3f4-ef89-4df1-a37b-ec368599fb48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'orange-text': listData.selected.length > 0}</value>
      <webElementGuid>278569e6-cad3-4eb5-82e9-6c74288bf060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>more_horiz</value>
      <webElementGuid>10c47d19-911e-47d0-8c5d-4242fce5794d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;languagesDiv&quot;)/crud-panel[1]/div[@class=&quot;form-div&quot;]/div[@class=&quot;list-container&quot;]/list[1]/table[@class=&quot;highlight bordered&quot;]/thead[1]/tr[1]/th[@class=&quot;list-options&quot;]/a[@class=&quot;dropdown-button dropdown&quot;]/i[@class=&quot;material-icons icons-color orange-text&quot;]</value>
      <webElementGuid>004f1f3f-5ba5-491e-9c57-5b6d9754ad53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='languagesDiv']/crud-panel/div/div/list/table/thead/tr/th/a/i</value>
      <webElementGuid>34753a29-96c3-4c87-892d-73175569233f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Timesheet'])[2]/following::i[1]</value>
      <webElementGuid>48f4d034-f7dd-4075-b90c-3b7c37890eb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit Request'])[2]/following::i[1]</value>
      <webElementGuid>60417ecf-8dbb-497b-b5cc-955b18a437da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[1]/preceding::i[1]</value>
      <webElementGuid>f630af4c-1c8d-470b-8ac7-06a0a4112a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deselect All'])[1]/preceding::i[1]</value>
      <webElementGuid>116b59c4-5fc2-4d81-842c-361781e92ac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='more_horiz']/parent::*</value>
      <webElementGuid>345ce7a8-ba4b-46c2-a783-26024b55f570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/a/i</value>
      <webElementGuid>271dd6e9-1fc7-492c-ada8-afcea4210ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'more_horiz' or . = 'more_horiz')]</value>
      <webElementGuid>67be6391-ee7b-4987-ba2b-39dc6812ebaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='licenseDiv']/crud-panel/div/div/list/table/thead/tr/th/a/i</value>
      <webElementGuid>872a61f6-12b7-4594-8836-557ffefd7dc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
