<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label2</name>
   <tag></tag>
   <elementGuidId>c527e9ff-37f6-4b37-a286-cf5eb47ae707</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td > label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;licenseDiv&quot;]/crud-panel/div/div/list/table/tbody/tr[1]/td[1]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Addnewtwo ohrm_edit&quot;i] >> label</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3f54f154-df43-4c25-9439-e965932f78ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>checkbox_list0_44</value>
      <webElementGuid>2753f90d-be29-4cbb-99b0-b2940d8baf57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;licenseDiv&quot;)/crud-panel[1]/div[@class=&quot;form-div&quot;]/div[@class=&quot;list-container&quot;]/list[1]/table[@class=&quot;highlight bordered&quot;]/tbody[1]/tr[2]/td[1]/label[1]</value>
      <webElementGuid>a98875a4-cee4-423b-9de2-2ef1f4498448</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='licenseDiv']/crud-panel/div/div/list/table/tbody/tr[2]/td/label</value>
      <webElementGuid>a07f07cd-515f-4f5f-8367-c43d12425367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/label</value>
      <webElementGuid>0b336d41-8c38-492f-b24f-60db7dd95627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='licenseDiv']/crud-panel/div/div/list/table/tbody/tr/td/label</value>
      <webElementGuid>25543e72-d550-4074-aaa7-38cc724c0950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>d4bfd6a6-46e6-485c-8df3-b4aa535216aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
